### ISSUE TITLE
Events missing on web dashboard.

### ISSUE THREAD

**Issue by yarikpwnzer** [mixpanel/mixpanel-react-native#106]
I see only 'Create Alias' event, but all my events are missing. In MP logs everything is fine:
2021-10-14 00:49:14.858146+0300 Albion[40870:377518] [javascript] 'MIXPANEL', { token: 'MY_TOKEN',
[Mixpanel - MixpanelInstance.swift - func loggingEnabled] (info) - Logging Enabled
[Mixpanel - MPDB.swift - func open()] (info) - Successfully opened connection to database at path: /Users/yarik/Library/Developer/CoreSimulator/Devices/33D5CDC2-BC4D-44A0-9209-13076E17D93C/data/Containers/Data/Application/4C9241B8-6658-40E5-A987-45FDAB712026/Library/MY_TOKEN_MPDB.sqlite
[Mixpanel - MPDB.swift - func createTableFor(_:)] (info) - mixpanel_ MY_TOKEN_events table created
[Mixpanel - MPDB.swift - func createTableFor(_:)] (info) - mixpanel_ MY_TOKEN_people table created
[Mixpanel - MPDB.swift - func createTableFor(_:)] (info) - mixpanel_ MY_TOKEN_groups table created
2021-10-14 00:49:14.890918+0300 Albion[40870:377518] [javascript] 'mixpanel deviceId', '69F6247F-5472-48C4-92FE-FD03AA78B272'
[Mixpanel - MPDB.swift - func updateRowsFlag(_:newFlag:)] (info) - Succesfully update rows from table mixpanel_ MY_TOKEN_people
[Mixpanel - MPDB.swift - func insertRow(_:data:flag:)] (info) - Successfully inserted row into table mixpanel_ MY_TOKEN_events **<<<<<---------- My event!**

My setup:
```js
export const identifyUser = createAsyncThunk(
  'mixpanel/identifyUser',
  async (_, { getState, dispatch }) => {
    const { mixpanelAliasWasCreated } = getState().settings;
    mixpanel = await Mixpanel.init('My Token');
    mixpanel.setLoggingEnabled(true);
    if (!mixpanel) {
      console.log('Mixpanel instance was not initialized!');
      return;
    }
    const distinctId = await mixpanel.getDistinctId();
    const deviceId = getUniqueId();
    if (!mixpanelAliasWasCreated) {
      mixpanel.alias(deviceId, distinctId);
      mixpanel.getPeople().set('Device Id', deviceId);
      dispatch(changeStorageData({ key: 'mixpanelAliasWasCreated', value: JSON.stringify(true) }));
    }
    mixpanel.identify(deviceId);
  }
);

export const trackMixpanelEvent = (name, properties) => {
  if (!mixpanel) {
    console.log('Mixpanel instance was not initialized on track event!');
    return;
  }
  mixpanel.track(name, properties);
};
```

P.S. My app haven't login/register (not needed) so I'm using device unique id as identifier.

**Comment by yarikpwnzer** [comment]
<img width="841" alt="Знімок екрана 2021-10-14 о 01 04 42" src="https://user-images.githubusercontent.com/5438263/137219077-bb89b411-193b-4049-921d-9b6d6aca21b7.png">

**Comment by yarikpwnzer** [comment]
@zihejia downgraded to 1.3.3 now I see more logs when I'm trying to send events, but still I don't see events on dashboard:
```
[Mixpanel - MixpanelInstance.swift - func loggingEnabled] (info) - Logging Enabled
[Mixpanel - Track.swift - func track(event:properties:eventsQueue:timedEvents:superProperties:distinctId:anonymousId:userId:hadPersistedDistinctId:epochInterval:)] (debug) - adding event to queue
[Mixpanel - Track.swift - func track(event:properties:eventsQueue:timedEvents:superProperties:distinctId:anonymousId:userId:hadPersistedDistinctId:epochInterval:)] (debug) - ["event": "Price Check", "properties": ["time": 1634292016, "$user_id": "69F6247F-5472-48C4-92FE-FD03AA78B272", "$had_persisted_distinct_id": false, "$screen_width": 390, "Unique Name": "T4_HEAD_CLOTH_HELL@1", "Screen": "Search", "$screen_height": 844, "distinct_id": "69F6247F-5472-48C4-92FE-FD03AA78B272", "$device_id": "F5D7BAD3-86B3-4679-A315-7BC705318BC7", "token": "token", "$manufacturer": "Apple", "$app_version_string": 1.0, "$lib_version": "1.3.3", "$os_version": "14.1", "mp_lib": "react-native", "$radio": "None", "$os": "iOS", "$model": "x86_64", "$app_build_number": 1, "$carrier": "", "$wifi": true], "$mp_metadata": ["$mp_event_id": "4866e391f213ce14", "$mp_session_id": "fd8d8f97d9ac89ff", "$mp_session_seq_id": 0, "$mp_session_start_sec": 0]]
[Mixpanel - Track.swift - func track(event:properties:eventsQueue:timedEvents:superProperties:distinctId:anonymousId:userId:hadPersistedDistinctId:epochInterval:)] (debug) - adding event to queue
[Mixpanel - Track.swift - func track(event:properties:eventsQueue:timedEvents:superProperties:distinctId:anonymousId:userId:hadPersistedDistinctId:epochInterval:)] (debug) - ["$mp_metadata": ["$mp_session_id": "fd8d8f97d9ac89ff", "$mp_session_seq_id": 1, "$mp_event_id": "99f9e39a1c95e170", "$mp_session_start_sec": 0], "properties": ["$user_id": "69F6247F-5472-48C4-92FE-FD03AA78B272", "mp_lib": "react-native", "time": 1634292111, "$os_version": "14.1", "$had_persisted_distinct_id": false, "$carrier": "", "distinct_id": "69F6247F-5472-48C4-92FE-FD03AA78B272", "$screen_height": 844, "$device_id": "F5D7BAD3-86B3-4679-A315-7BC705318BC7", "$wifi": true, "Unique Name": "T4_HEAD_CLOTH_HELL@2", "$screen_width": 390, "$app_version_string": 1.0, "$radio": "None", "$model": "x86_64", "token": "c089832213e13e3ceeeaa66d55fcc65e", "$manufacturer": "Apple", "Screen": "Search", "$os": "iOS", "$lib_version": "1.3.3", "$app_build_number": 1], "event": "Craft Check"]
```

**Comment by SimonVuong** [comment]
FYI, I have the same problem on iOS. Didn't check Android, but iOS is not 'auto-flushing' every 60 seconds

**Comment by Nodirbek-Sharipov** [comment]
on ios, no solution so far, you better tell me what is wrong. I did everything I could, went through your docs several times, not a beginner or retarded coder here, actual software engineer, struggling to send some dumb ass event to your service for 2 days straight. I could have done something productive if I did not waste my life questioning your dumb codebase

sincerely yours

**Comment by yarikpwnzer** [comment]
Yeah it's a bug, it's not auto-flushing every 60 seconds as @SimonVuong mention.
@Nodirbek-Sharipov +1 I had same thoughts that time, and I was so angry. I remember: 'OK I need 20 min to plug MP sdk and continue my main work' how was I wrong (8+ years of coding experience and I remember I helped to close 3 critical issues on their MP iOS library, once they forgot to return callback on their AB testing, and we had a real issues on production)  :D I see unofficial react-native sdk works even better than official, this is nonsense.
@zihejia I believe this bug should be reopened.

**Comment by Nodirbek-Sharipov** [comment]
so shame that non official libs work better than the official one. I am using this one: https://www.npmjs.com/package/react-native-mixpanel
