### ISSUE TITLE
setGroup array properties

### ISSUE THREAD

**Issue by sam-houle1** [mixpanel/mixpanel-react-native#108]
Hi, I'm using the setGroup fonction from Mixpanel, I noticed the group value in the JS documentation specify we can send an array of value instead of a string, but the react-native version does not seems to parse array. I tried to pass an array and the property in mixpanel displays has a double array.

Here's the [link](https://developer.mixpanel.com/docs/javascript-full-api-reference#mixpanelset_group) to the API reference.

**Comment by zihejia** [comment]
hi @sam-houle1 , sorry for the late response, we will address this issue and make it consistent with JS.

**Comment by zihejia** [comment]
hi @sam-houle1 , again, thanks for bringing it up. This issue has been fixed in [1.3.5](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v1.3.5). I'm closing this issue now, please feel free to reopen if the problem still exists.
