### ISSUE TITLE
Cannot get users properties?

### ISSUE THREAD

**Issue by jfbn** [mixpanel/mixpanel-react-native#113]
I am looking through the docs, and it appears that there is no way for me to programatically access the properties of the Mixpanel user?
I have looked through the source code and it seems that there just aren't exposed any functions to access the users properties, only to access the super properties.

Surely this is not a unusual use case? What are my opions? 

I want to do this to know the country of the user.

**Comment by zihejia** [comment]
Hi @jfbn , some of the user properties like the geolocation (country) are calculated on the server side so we don't have access from the SDK. But you can query the Mixpanel API directly to get that information.  Please check the document: https://developer.mixpanel.com/reference/engage-query
