### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by tehmou** [mixpanel/mixpanel-react-native#12]
Amazing we have the official RN library out - just in time for our integration!

However, as per convention I've tried installing @types/mixpanel-react-native to get the types right but this package does not seem to exist. Is there a way to get the TypeScript types for the library?

**Comment by zihejia** [comment]
hi @tehmou, we will add typescript support soon.

**Comment by mtzfactory** [comment]
Looking forward to it!

**Comment by izakfilmalter** [comment]
Also really looking forward to ts support.

**Comment by taschik** [comment]
Hi @zihejia do you guys already have a timeline for the TS support that you could share with us?

**Comment by sroy3** [comment]
I created a PR (https://github.com/mixpanel/mixpanel-react-native/pull/29) for that a week ago, but still no feedback on it.

**Comment by zihejia** [comment]
Hi guys, sorry for the delay. Now the typescript definition has been added in v1.1.1. Thanks @sroy3 for providing the PR. I'm closing this issue now, please feel free to reopen for any issue. Thank you!
