### ISSUE TITLE
Inconsistencies on iOS compared to using older Mixpanel library

### ISSUE THREAD

**Issue by ilyausorov** [mixpanel/mixpanel-react-native#120]
Hey there,

Wanted to ask the Mixpanel team why I'm seeing the following, what looks like, inconsistencies after upgrading to this library **for iOS** (was previously using react-native-mixpanel, which was using the "iphone" mp_lib version 3.6.5):

1) For the First App Open event ($ae_first_open), I'm seeing the "mp_lib" value as "swift", while for all other events I'm seeing the "mp_lib" value as "react-native". In my dashboards, I have funnels where they are broken down by Mixpanel Library, which previously was either "iphone" or "android" but now because the First App Open event has a different "mp_lib" value, it breaks my funnel reports. See 1st screenshot for $ae_first_open event and 2nd screenshot for another custom event.

2) The First App Open event seems to be firing later than at the beginning of the user's event stream, which again is screwing up my funnel reports because prior to this I was making the assumption (which I hope was a reasonable) that First App Open would be at the beginning of the user's event stream (which it has been with the prior library). This was how I was identifying a user going through the first time onboarding flow, as opposed to coming back to the sign up / login screen later.

3) Create Alias has not been reliably aliasing my users and I'm seeing cases of not connected profiles between anonymous and signed up users. See 3rd screenshot. What I'm doing for alias is the following:
```
export const createAlias = async (userId) => {
  const distinctId = await Mixpanel.getDistinctId();
  Mixpanel.alias(userId, distinctId);
};
```

<img width="535" alt="First App Open Event" src="https://user-images.githubusercontent.com/16529964/148138290-0e30a21a-078f-4ddf-8437-65797565e208.png">

<img width="539" alt="Page Load Event" src="https://user-images.githubusercontent.com/16529964/148138297-a4bc09e2-bc38-4d9b-a67f-c850cba51cce.png">

<img width="1447" alt="Create Alias" src="https://user-images.githubusercontent.com/16529964/148138683-b3452f50-6065-4605-b40c-aed9c5ce28db.png">

It would much appreciate if we could have all events from this library coming with the same "mp_lib" value, including the "automatic events" and also to have the First App Open event happen at the start of the event stream. Thoughts on why the aliasing may not be happening reliably are also welcome. 

Looking forward to hearing the team's thoughts. Thanks.

Versions:
**iOS Only**
"react-native": "0.63.4",
"mixpanel-react-native": "^1.3.4",

**Comment by zihejia** [comment]
hi @ilyausorov , thanks for bringing it up. We will address these issues.

**Comment by ilyausorov** [comment]
Sounds great. Let me know if I can help with any more info.

**Comment by zihejia** [comment]
Hi @ilyausorov , the issue 1 and 2 has been fixed. Please try 1.3.6. Let me know how it goes. Thanks!

**Comment by zihejia** [comment]
with the new `Identity Merge` enabled on the project, calling `alias` is no longer required. Please check this doc: https://help.mixpanel.com/hc/en-us/articles/360039133851-Moving-to-Identity-Merge.  I'm closing this one, please feel free to reopen if you have any questions.
