### ISSUE TITLE
`$app_version_string ` is being set as the version of the SDK rather than the version of the app itself (iOS only)

### ISSUE THREAD

**Issue by fuller** [mixpanel/mixpanel-react-native#121]
Using version 1.3.5 of `mixpanel-react-native`

Our current app version is set to `22.104.0` however we're seeing the `App Version` in Mixpanel set as `3.0.0`. It seems this may be mapped to the version of the underlying Swift SDK rather than the version of the app itself.

This is only happening on iOS and not Android.

![image](https://user-images.githubusercontent.com/2483304/148462203-59f2719d-6d87-4e7a-9489-2b609d9b782a.png)

**Comment by zihejia** [comment]
hi @fuller , the issue has been fixed 1.3.6. I'm closing this issue now, please feel free to reopen if the problem still exists.
