### ISSUE TITLE
Types for getPeople().set() missing option for multiple props

### ISSUE THREAD

**Issue by jpalmieri** [mixpanel/mixpanel-react-native#123]
It looks like `getPeople().set()` allows you to pass in an object of multiple props and values:

https://github.com/mixpanel/mixpanel-react-native/blob/4b3836366ff402b5b1c2ae352c8d29966330de5f/__tests__/index.test.js#L168-L172

but the types only reflect the single prop API:

https://github.com/mixpanel/mixpanel-react-native/blob/4b3836366ff402b5b1c2ae352c8d29966330de5f/index.d.ts#L38

**Comment by jaredmixpanel** [comment]
@jpalmieri This issue should be fixed in `v1.3.8`, please feel free to re-open if any issue persists.
