### ISSUE TITLE
SIGSEGV Segmentation violation for old devices: Samsung S5 (android 6.0.1), Oneplus2 (Android 6.0.1)

### ISSUE THREAD

**Issue by alexrymkevich** [mixpanel/mixpanel-react-native#126]
Tried to update library to official, but unfortunately had this problem. 
Application is working fine with prev no official library "react-native-mixpanel": "^1.2.5",

SIGSEGV Segmentation violation (invalid memory reference) 
    /system/lib/libart.so:903112 0xb3b017c8

Problem reproduced only on production mode. and works fine on debug mode and for new devices 

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/6214382/154975705-b97129b2-bd63-40a3-9773-6b1f4ac1ef11.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/6214382/154976257-127e618a-89c4-4e5b-8007-89dc9a616b19.png">

**Comment by alexrymkevich** [comment]
Any updates?

**Comment by zihejia** [comment]
hi @alexrymkevich , sorry for the late response. To be able to assist you more easily, do you have a more detailed log showing Mixpanel code being referenced or a sample app that you can reproduce? Without these, it's hard to investigate further.

**Comment by alexrymkevich** [comment]
No, I already removed this code and rollbacked to prev library

**Comment by theambidextrous** [comment]
@alexrymkevich this issue is happening(Segmentation fault - accessing deallocated memory location ) on ios with mixpanel-react-native:2.3.1. what version worked for you?

System info

```
System:
    OS: macOS 12.6.8
    CPU: (10) arm64 Apple M1 Max
    Memory: 650.33 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.12 => 0.71.12  
```
