### ISSUE TITLE
"First App Open" event not being tacked on iOS

### ISSUE THREAD

**Issue by billkim84** [mixpanel/mixpanel-react-native#128]
"mixpanel-react-native": "1.3.5",

Only ios has the issue. 
![image](https://user-images.githubusercontent.com/2604192/155465210-28f065e7-6bcb-425c-9b22-e6399039e8cd.png)

**Comment by zihejia** [comment]
hi @billkim84 , the issue should have been fixed in v1.3.7. I'm closing this one now, but feel free to reopen if the problem still exits.
