### ISSUE TITLE
Events not being tracked

### ISSUE THREAD

**Issue by 0xsaranonearth** [mixpanel/mixpanel-react-native#136]
None of the events in a specific screen being tracked for some reason although the events in other parts of the app are being tracked fine.

**Comment by zihejia** [comment]
hi @0xsaranonearth , could you provide more information about which version are you using and which platform(ios/android) you are facing this issue?

In the meantime, here are some tips from our doc

Why aren't my events showing up?
To preserve battery life and customer bandwidth, the Mixpanel library doesn't send the events you record immediately. Instead, it sends batches to the Mixpanel servers every 60 seconds while your application is running, as well as when the application transitions to the background. You can call [flush()](https://mixpanel.github.io/mixpanel-react-native/Mixpanel.html#flush) manually if you want to force a flush at a particular moment.

mixpanel.flush();
If your events are still not showing up after 60 seconds, check if you have opted out of tracking. You can also enable Mixpanel debugging and logging, it allows you to see the debug output from the Mixpanel library. To enable it, call [setLoggingEnabled](https://mixpanel.github.io/mixpanel-react-native/Mixpanel.html#setLoggingEnabled) with true, then run your iOS project with Xcode or android project with Android Studio. The logs should be available in the console.

mixpanel.setLoggingEnabled(true);

**Comment by zihejia** [comment]
I'm closing this one now due to no response but feel free to reopen or reach out to our support team.
