### ISSUE TITLE
Feature Request: Built in getInstance() or similar instead of custom tooling

### ISSUE THREAD

**Issue by princefishthrower** [mixpanel/mixpanel-react-native#139]
I notice as soon as you want to use `mixpanel` from any file other than where `mixpanel` is initialized, you would otherwise have to make your own singleton, like in the demo:

```
import {Mixpanel} from 'mixpanel-react-native';
import {token as MixpanelToken} from './app.json';


export class MixpanelManager {
    static sharedInstance = MixpanelManager.sharedInstance || new MixpanelManager();

    constructor() {
        this.mixpanel = new Mixpanel(MixpanelToken);
        this.mixpanel.init();
        this.mixpanel.setLoggingEnabled(true);
    }
}

export const MixpanelInstance = MixpanelManager.sharedInstance.mixpanel;
```

Libraries like sendbird (https://github.com/sendbird/sendbird-chat-sdk-javascript) have a `getInstance()` on their main export, so in this case, it would be something like the capitalized `Mixpanel.getInstance()` - returns null of course if it has been initialized yet.

This would prevent users from having to hand-roll something like the above code.

Interested to hear thoughts about this.

**Comment by hans-lizihan** [comment]
i usually just do this

```
import {Mixpanel} from 'mixpanel-react-native';
import {token as MixpanelToken} from './app.json';

export const mixpanel = new Mixpanel(MixpanelToken);
mixpanel.init();
mixpanel.setLoggingEnabled(true);
```
