### ISSUE TITLE
Events for Android not showing up when the app is on play store.

### ISSUE THREAD

**Issue by awadesmoline** [mixpanel/mixpanel-react-native#141]
This package doesn't work for android when the app is in the play store (I don't see production events in mixpanel). It only works in development. Any reason why that may be or how to fix it? Thanks for your help in advance.

**Comment by zihejia** [comment]
hi @awadesmoline , I'm so sorry for the late response. Do you still have this issue?

**Comment by awadesmoline** [comment]
No worries. No, the issue has been resolved. It was caused by a mistake in my configuration, which has been fixed.
