### ISSUE TITLE
Error: mixpanel-react-native: MixpanelReactNative is null

### ISSUE THREAD

**Issue by ewisaac** [mixpanel/mixpanel-react-native#142]
Hey there, we've followed the steps and instructions provided but this bug is still persisting. 

Error: mixpanel-react-native: MixpanelReactNative is null.
  Please follow the guide on the Github repository: https://github.com/mixpanel/mixpanel-react-native.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

**Comment by k1mmm** [comment]
Same issue here, using react-native-macos 0.66

**Comment by ofirgeller** [comment]
Same on android mixpanel-react-native.

It looks to me like a linking issue.

**Comment by fkeloks** [comment]
Same error

**Comment by laubsauger** [comment]
Jup, same here. 

Calling constructor 
```js
new Mixpanel(project_token, trackAutomaticEvents)
```

Crashes with error mentioned above.

**Comment by zachdorcinville21** [comment]
Also getting this error, only on Android

**Comment by GwFreak01** [comment]
Still crashing on 
```
"react-native": "0.71.8",
"expo": "^48.0.0",
"mixpanel-react-native": "^2.2.5",
```

Anyone have a work around?

**Comment by zihejia** [comment]
fixed in[ v2.3.0](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v2.3.0). Feel free to reopen if the problem still exists.

**Comment by helians11** [comment]
Error: mixpanel-react-native: MixpanelReactNative is null. 

Still getting this error.
mixpanel-react-native: ^2.3.1
react-native: 0.71.8

import { Mixpanel } from 'mixpanel-react-native';

const mixpanel = new Mixpanel(projectToken, true);

**Comment by OOCAZ** [comment]
Same issue as @helians11 

"mixpanel-react-native": "^2.3.1",
"react-native": "0.72.5",

Just using the sample code: 
```const mixpanel = new Mixpanel("Token Val", true);
mixpanel.init();
mixpanel.setLoggingEnabled(true);```
