### ISSUE TITLE
How get the alias of the current user using the react native SDK?

### ISSUE THREAD

**Issue by Albert-Gao** [mixpanel/mixpanel-react-native#143]
Seems we do not have the .get_property() as the js sdk?

**Comment by zihejia** [comment]
hi @Albert-Gao , we are not supporting it in RN atm, marking it as feature request. btw we are deprecating `alias` and you do not need to call `alias` if you enabled `Identity Merge`, using `identify` is enough.
https://help.mixpanel.com/hc/en-us/articles/360039133851-Moving-to-Identity-Merge

**Comment by Albert-Gao** [comment]
Thanks 😊

**Comment by MoeMamdouh** [comment]
@zihejia  The link is not opening
