### ISSUE TITLE
Mixpanel Initialization 

### ISSUE THREAD

**Issue by AbdullahQureshi1080** [mixpanel/mixpanel-react-native#144]
How to check if mixpanel is initialized or not?
I cannot find any documentation on this?

Example Scenario: If I created a custom hook isolating the logic of mixpanel initialization, the hook called first time would initialized the SDK but the second time it would not, assumption is that SDK would be already initialized in the background or the second time it does not require initialization even if the hook is called from a different place (another component).

How to check for this?

**Comment by zihejia** [comment]
HI @AbdullahQureshi1080 , you can use the singleton, you can check our sample app in this repo. 
App location: https://github.com/mixpanel/mixpanel-react-native/blob/master/Samples/MixpanelDemo
The isolated mixpanel initialization code: https://github.com/mixpanel/mixpanel-react-native/blob/master/Samples/MixpanelDemo/Analytics.js 
I'm closing this one now, feel free to reopen if you have further question.
