### ISSUE TITLE
Support new React Native new architecture (TurboModules/Fabric)

### ISSUE THREAD

**Issue by tom-sherman** [mixpanel/mixpanel-react-native#145]
See https://reactnative.dev/docs/new-architecture-library-intro

https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

**Comment by zihejia** [comment]
Sorry, we have no plan at the moment to support it as it is still in the experimental stage.

**Comment by tom-sherman** [comment]
@zihejia the new architecture is not experimental. It's ready to be adopted by the React Native community and has gaining wider support by the week in open source.

This library is a blocker for us moving to the new architecture. We're mixpanel customers but if there is no plan to support React Native then we would have to consider moving to a different analytics provider.
