### ISSUE TITLE
Events are not shown on dashboard

### ISSUE THREAD

**Issue by usamaabutt** [mixpanel/mixpanel-react-native#148]
Hi everyone - I am facing an issue with mixpanel in my react-native project. I have setup everything but I am not getting mixpanel track events back on dashboard.

Can anyone please guide me on that what I am missing?

FYI: I am testing it in development mode on the iOS simulator and already set the `setLoggingEnabled` true.

cc: [zihejia](https://github.com/zihejia)

**Comment by zihejia** [comment]
Hi @usamaabutt ,  In case you don't know, to preserve battery life and customer bandwidth, the Mixpanel library doesn't send the events you record immediately. Instead, it sends batches to the Mixpanel servers every 60 seconds while your application is running, as well as when the application transitions to the background. You can call [flush()](https://mixpanel.github.io/mixpanel-react-native/Mixpanel.html#flush) manually if you want to force a flush at a particular moment.
```
mixpanel.flush()
```

If that does not help. Have you tried running the iOS app with Xcode? If you have `setLoggingEnabled` true, you should be able to see logs from the Xcode console. Feel free to paste the log in here. 

Also, have you tried setting your server to mixpanel EU server? If that is the case, you might need to log in to EU server to check your events.
