### ISSUE TITLE
How to use this library with Expo?

### ISSUE THREAD

**Issue by wtfzambo** [mixpanel/mixpanel-react-native#149]
Hello,

I hope someone can give me a hint on how to make `mixpanel-react-native` work on an [expo app](https://docs.expo.dev/) in windows11.

This is what I am currently doing:

```sh
expo init MyProject
# then I select `minimal`
cd MyProject
yarn add mixpanel-react-native
expo start
```

Everything is fine, but the moment I add to `App.js`

```js
import { Mixpanel } from 'mixpanel-react-native';
const mixpanel = new Mixpanel('MY_TOKEN');
mixpanel.init();
```

I run into the dreaded error: `MixpanelReactNative is null` both on web and Expo Go on android.
Now I understand that Expo Go doesn't support mixpanel, but shouldn't I at least be able to run it on web?

Any help is much appreciated.

---

**My `App.js`**
<details>
  <summary>Click to expand</summary>

```js
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Mixpanel } from 'mixpanel-react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
</details>

**My system**
<details>
  <summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/47462792/176193445-3b8ab601-15f4-4bd5-868e-cb6caba3446f.png)

</details>

**Comment by alexander01202** [comment]
Also need this too. Native plugins can now be added through config plugins in expo prebuilt project

**Comment by wtfzambo** [comment]
> Also need this too. Native plugins can now be added through config plugins in expo prebuilt project

Ah, good to know! Can you point me to the docs mentioning this?

**Comment by fr3fou** [comment]
did you figure this out?

**Comment by zihejia** [comment]
Let's refer to the issue: https://github.com/mixpanel/mixpanel-react-native/issues/82
