### ISSUE TITLE
Execution failed for task ':mixpanel-react-native:parseDebugLocalResources'.

### ISSUE THREAD

**Issue by rusakovic** [mixpanel/mixpanel-react-native#152]
Hello. Could you, please, help to debug?

Issue occurs during Android building.

`"react-native": "^0.67.4",`
`"mixpanel-react-native": "1.5.0",`

```
* What went wrong:
Execution failed for task ':mixpanel-react-native:parseDebugLocalResources'.
> Could not resolve all files for configuration ':mixpanel-react-native:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: 
/Library/Android/sdk/platforms/android-30/android.jar.
         > /Library/Android/sdk/platforms/android-30/android.jar
```

**Comment by zihejia** [comment]
Hi @rusakovic, I apologize for the delayed response. Please try using the latest version of Mixpanel for React Native. It appears that some Android configuration files may be missing. I recommend reinstalling the Android SDK, specifically for version 30. If the problem persists, feel free to reopen this issue
