### ISSUE TITLE
Android build is failing.

### ISSUE THREAD

**Issue by jpm8888** [mixpanel/mixpanel-react-native#154]
"react": "18.2.0",
"react-native": "0.69.4",
"mixpanel-react-native": "1.5.0",

`> Task :app:compressReleaseAssets
Execution optimizations have been disabled for task ':app:compressReleaseAssets' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/jpm/workspace/rn_projects/kelly-mobile-app/android/app/build/intermediates/assets/release/mergeReleaseAssets'. Reason: Task ':app:compressReleaseAssets' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :mixpanel-react-native:verifyReleaseResources FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mixpanel-react-native:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/jpm/.gradle/caches/transforms-3/49eaca889f9ab764516b333d9aee56e1/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
`

**Comment by dpyeates** [comment]
I'm also seeing this. It only occurs on a release build. Debug builds seem to be ok. Any thoughts?

**Comment by jpm8888** [comment]
I fixed this issue by using `app:` 

`./gradlew app:assembleRelease`

**Comment by jqn** [comment]
@jpm8888 fix worked for me too but what's the reason that works? any thoughts

**Comment by jpm8888** [comment]
Don't know bro.
🍻🍻
