### ISSUE TITLE
iOS: App crash on init mixpanel sdk

### ISSUE THREAD

**Issue by bharatbrovitech** [mixpanel/mixpanel-react-native#156]
ios platform: 14.5
Version: "mixpanel-react-native": "^2.0.0",
Device: Emulator

**Issue:** 
on **mixpanel.init()** throwing an exception

"Exception **'initialize:optOutTrackingByDefault:properties:resolver:rejecter:** is not a recognized Objective-C method.' was thrown while invoking initialize on target MixpanelReactNative with params?

**Comment by jaredmixpanel** [comment]
@bharatbrovitech a fix has been published in v2.0.1

**Comment by bharatbrovitech** [comment]
@jaredmixpanel It's fixed. Thanks 👍
