### ISSUE TITLE
com.facebook.react.bridge.NativeArgumentsParseException: MixpanelReactNative.track got 5 arguments, expected 6

### ISSUE THREAD

**Issue by DeepakM02** [mixpanel/mixpanel-react-native#161]
Platform: Android 
Version: "mixpanel-react-native": "^2.0.1"

Issue:
com.facebook.react.bridge.NativeArgumentsParseException: MixpanelReactNative.track got 5 arguments, expected 6

App crashes after starting the app

**Comment by DeepakM02** [comment]
@jaredmixpanel Please look into it

**Comment by jaredmixpanel** [comment]
@DeepakM02 this issue should be fixed in `v2.1.0`. please update and if the issue persists feel free to re-open.
