### ISSUE TITLE
Old async initialization of mixpanel crashes on android

### ISSUE THREAD

**Issue by ToyboxZach** [mixpanel/mixpanel-react-native#162]
I had code that was initializing mixpanel the old way:
```
Mixpanel.init("TOKEN HERE", false)
        .then((mixpanel) => {
```

And was getting a crash

moving to the new style resolved it
```
 const mixpanel = new Mixpanel("TOKEN HERE", false);
 mixpanel.init();
```

This should probably be mentioned somewhere if it is not supported any more, if not then hopefully just this bug being findable can help other people who run into the same issue.

**Comment by zihejia** [comment]
Though the class method has been deprecated, this issue has been fixed in [v2.3.0](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v2.3.0) so it won't crash anymore. Thanks for bringing it up.
