### ISSUE TITLE
resource android:attr/lStar not found

### ISSUE THREAD

**Issue by sidferreira** [mixpanel/mixpanel-react-native#164]
I'm trying to build the app with React Native 0.70.1 but I'm continuously facing the following error:

```
 What went wrong:
Execution failed for task ':mixpanel-react-native:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/.../node_modules/mixpanel-react-native/android/build/intermediates/merged_res/release/values/values.xml:2722: AAPT: error: resource android:attr/lStar not found
```

**Comment by filozof6** [comment]
I have the same problem and I cant get it fixed either

**Comment by sidferreira** [comment]
@filozof6 gradle clean then gradle app:assemblerelease

**Comment by filozof6** [comment]
> @filozof6 gradle clean then gradle app:assemblerelease

i am still facing the same issue, can yo ushow my your gradle files?

**Comment by thecodecafe** [comment]
Facing this issue as well, I'm using React Native 0.70.1

**Comment by sidferreira** [comment]
@thecodecafe @filozof6 

My steps:
1) did run `./gradlew clean`
2) did run `./gradlew app:assembleRelease` from the `android` folder (not `./android/gradlew app:assembleRelease -p android`. For fastlane I had to use `chdir` around it.

**Comment by filozof6** [comment]
> @thecodecafe @filozof6
> 
> My steps:
> 
> 1. did run `./gradlew clean`
> 2. did run `./gradlew app:assembleRelease` from the `android` folder (not `./android/gradlew app:assembleRelease -p android`. For fastlane I had to use `chdir` around it.

yeah i was using `./gradlew assembleRelease` which was failing prefixing the assembleRelease with app: fixed the issue for me

**Comment by StampixSMO** [comment]
I'm having this issue all of a sudden as well when just running `yarn android --deviceId ...`, very odd.

**Comment by lucasbeatdapp** [comment]
@sidferreira would you be able to describe how you are using `chdir` with fastlane? I took a look at Fastlane's documentation and there is not a lot of help in terms of setting it up.

**Comment by dragosbln** [comment]
In my case, I ran into the error when running the app in debug mode, with `npx react-native run-android`, so the solution with `./gradlew app:assembleRelease` didn't work for me.

After some digging, I found out that the lStar attribute that's mentioned in the error requires that `compileSdkVersion` and `compileSdkVersion` are set to 31, while in `node_modules/mixpanel-react-native/android/build.gradle`, those were set to 30.

After I changed it to 31, the issue was gone and the app was building successfully. Here's the patch that does the trick:

**mixpanel-react-native+2.1.0.patch**
```
diff --git a/node_modules/mixpanel-react-native/android/build.gradle b/node_modules/mixpanel-react-native/android/build.gradle
index 175faa7..5e86e62 100644
--- a/node_modules/mixpanel-react-native/android/build.gradle
+++ b/node_modules/mixpanel-react-native/android/build.gradle
@@ -11,11 +11,11 @@ buildscript {
 apply plugin: 'com.android.library'
 
 android {
-    compileSdkVersion 30
+    compileSdkVersion 31
     buildToolsVersion "30.0.3"
     defaultConfig {
         minSdkVersion 21
-        targetSdkVersion 30
+        targetSdkVersion 31
         versionCode 1
         versionName "1.0"
}
```

**Comment by xaviermarchal** [comment]
@dragosbln interesting. Worked for me as well. Don't you think a PR should be done?
