### ISSUE TITLE
Add info about Expo development client in README

### ISSUE THREAD

**Issue by elmaxe** [mixpanel/mixpanel-react-native#166]
To run this app with Expo, you apparently need to have development builds set up (if you do not want to eject). I had to read https://github.com/mixpanel/mixpanel-react-native/issues/82 to figure that out

I suggest this should be added to the README to make it clear for people who use Expo

**Comment by zihejia** [comment]
thanks @elmaxe  for bringing it up, added [here](https://github.com/mixpanel/mixpanel-react-native/blob/master/README.md#for-expo-support-please-refer-to-this-issue)
