### ISSUE TITLE
Different behaviour between iOS and Android

### ISSUE THREAD

**Issue by fullstack17** [mixpanel/mixpanel-react-native#167]
Here are the codes that I set:
```
const distinctId = await analytics.getDistinctId();
analytics.alias('...', distinctId);
analytics.identify('...');
// event property
analytics.track('Account Created');
// user property
analytics.getPeople().set({
  ...
});
```
As you can see on the attached screenshot, on iOS there is  property - `User ID`, but on Android, it's not there.
Not sure if it's normal behaviour.
<img width="1757" alt="Screenshot 2022-11-16 at 23 16 53" src="https://user-images.githubusercontent.com/44271282/202286005-f58807be-078d-4e6b-a876-94caba097aa1.png">

**Comment by zihejia** [comment]
Hi @fullstack17, I apologize for the delayed response. Yes, this is the expected behavior, as our React Native (RN) SDK is a wrapper around both our iOS SDK and Android SDK. Unfortunately, there are slight differences between the behaviors of our iOS and Android SDKs.
