### ISSUE TITLE
TypeScript error TS1016: Required parameter following optional in Mixpanel.trackWithGroups

### ISSUE THREAD

**Issue by m0rl** [mixpanel/mixpanel-react-native#168]
Using the latest version of the library results in a TypeScript error:  

> error TS1016: A required parameter cannot follow an optional parameter

[In the index.d.ts](https://github.com/mixpanel/mixpanel-react-native/blob/0c4765793fba52fe3365aadae8422e3c02c4d6e0/index.d.ts#L20) file `trackWithGroups` is defined as:

```typescript
trackWithGroups(eventName: string, properties?: MixpanelProperties, groups: MixpanelProperties): void;
```

where an optional argument `properties` is followed by  `groups` which is required.  

From the [native integration code](https://github.com/mixpanel/mixpanel-react-native/blob/0c4765793fba52fe3365aadae8422e3c02c4d6e0/ios/MixpanelReactNative.swift#L316) it looks like both of these arguments can be defined as optional (and that should resolve the typecheck error).

Thanks!

**Comment by zihejia** [comment]
hi @m0rl , thanks for bringing it up. Do you mind creating a PR for this?

**Comment by m0rl** [comment]
> hi @m0rl , thanks for bringing it up. Do you mind creating a PR for this?

Sure, updated the type definition in #169
