### ISSUE TITLE
[QUESTION] Is the distinct id the same between sessions?

### ISSUE THREAD

**Issue by luisfuertes** [mixpanel/mixpanel-react-native#172]
Im checking this point on documentation:

https://help.mixpanel.com/hc/en-us/articles/115004509426-Distinct-ID-Creation-JavaScript-iOS-Android-

I have the question if the distinct id is the same between different sessions as long as the app is not uninstalled or if it can change?

Is it a reliable field to track anonymous users?

Thank you and sorry if this question should not go here but it is not clear to me if iOS distinct id without MIXPANEL_UNIQUE_DISTINCT_ID=1 continue being unique

**Comment by zihejia** [comment]
hi @luisfuertes , yes, the distinct id is the same as long as the app is not uninstalled. If MIXPANEL_UNIQUE_DISTINCT_ID=1  then it will keep the same regardless of the app ever being uninstalled.
