### ISSUE TITLE
Mixpanel causes android app when enableProguardInReleaseBuilds=true

### ISSUE THREAD

**Issue by Kazion500** [mixpanel/mixpanel-react-native#177]
My app crashes on android if i set enableProguardInReleaseBuilds=true not sure why build this doesn't happen when debug is true. 

Anyone know what could be causing this?

**Comment by zihejia** [comment]
hi @Kazion500 , you're using ProGuard so you need to add the following rule to android/app/proguard-rules.pro:
`-keep class com.facebook.jni.** { *; }`

please checkout the breaking changes in the RN release notes: https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#breaking

<img width="1106" alt="image" src="https://github.com/mixpanel/mixpanel-react-native/assets/36679208/ef575778-bea6-46e8-af18-5f39c143dea3">
