### ISSUE TITLE
Null reference used for synchronization (monitor-enter)

### ISSUE THREAD

**Issue by jcaviedesc** [mixpanel/mixpanel-react-native#189]
![Screenshot_2023-04-26-07-22-57-280_com nbn23 fansapp (2)](https://user-images.githubusercontent.com/19734429/234575029-fbd4928c-606c-4d42-b272-eb1416f00391.jpg)

### System Info
```bash
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 116.55 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2023.04.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /Users/juancamilo/.sdkman/candidates/java/current/bin/javac
    Python: 3.11.0 - /Users/juancamilo/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.5 => 0.63.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
### Project info
 - react-native: 0.63.5
 - mixpanel-react-native: ^2.1.0

### Description of error
I was working on the iOS platform, I changed the mixpanel token and went back to work with android and the application threw this error.

I try to run `./gradlew clean ` and reinstall package modules by runing `rm -rf node_modules && yarn install` but it does not work

**Comment by zihejia** [comment]
Hi @jcaviedesc , thanks for bringing it up. It is fixed in [v2.3.0](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v2.3.0). Feel free to reopen it if the problem still exists.
