### ISSUE TITLE
[error] MixpanelReactNative.initialize was called with 4 arguments but expects 5 arguments

### ISSUE THREAD

**Issue by trackwell-mike** [mixpanel/mixpanel-react-native#194]
We recently updated our version of `mixpanel-react-native` from `1.3.4` to `2.2.5`. Because we upgraded to v2, which introduced a [breaking change](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v2.0.0), we are now passing a boolean value for `trackAutomaticEvents`.

When we start our RN app, we are getting the following error:
```
MixpanelReactNative.initialize was called with 4 arguments but expects 5 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
```
![Screenshot 2023-05-23 at 6 14 12 PM](https://github.com/mixpanel/mixpanel-react-native/assets/61172689/8f550f19-557c-4282-91cc-3153d2395db4)

Our init code look like this:

```
import { Mixpanel } from 'mixpanel-react-native';
import Secrets from 'react-native-config';

export default class MixpanelManager {
  static sharedInstance =
    MixpanelManager.sharedInstance || new MixpanelManager();

  constructor() {
    this.configMixpanel();
  }

  configMixpanel = async () => {
    const trackAutomaticEvents = true;
    this.mixpanel = await Mixpanel.init(
      Secrets.MIXPANEL_TOKEN,
      trackAutomaticEvents
    );
    this.mixpanel.setLoggingEnabled(true);
  };

  ...
```

Relevant package versions:

```
node: "16.15.0"
npm: "9.6.6"
mixpanel-react-native: 2.2.5
react-native: 0.65.3
```

Any suggestions on how we might resolve, other than reverting back to v1?

**Comment by zihejia** [comment]
hi @trackwell-mike , please try the latest version v2.3.0 which contains the fix. However, the class method of Mixpanel init() is deprecated. To initialize Mixpanel, please use the instance method init() instead. See the example here: https://github.com/mixpanel/mixpanel-react-native/blob/master/Samples/SimpleMixpanel/App.js
