### ISSUE TITLE
[iOS] Incorrect iPhone model

### ISSUE THREAD

**Issue by makarkotlov** [mixpanel/mixpanel-react-native#195]
There are entries like iPhone15,2 or iPhone10,6 on the mixpanel dashboard which is incorrect since iPhone 15 is not yet released

<img width="250" alt="image" src="https://github.com/mixpanel/mixpanel-react-native/assets/32848434/56bf3dc9-0f64-47c6-83a5-e0d6275850de">

<img width="227" alt="image" src="https://github.com/mixpanel/mixpanel-react-native/assets/32848434/80393728-93f1-4d24-90ab-9209a2e012bb">

Lib version: 2.2.5
RN version: 0.69.9

**Comment by zihejia** [comment]
hi @makarkotlov , the Model number is not the same thing as the generation number, please check this wiki here: https://www.theiphonewiki.com/wiki/Models
