### ISSUE TITLE
I can't receive any events on android

### ISSUE THREAD

**Issue by lucyblake2023** [mixpanel/mixpanel-react-native#201]
![Ảnh màn hình 2023-06-14 lúc 21 39 44](https://github.com/mixpanel/mixpanel-react-native/assets/132081494/5e7a36bc-892f-4630-aea6-e203bcc86801)
On ios it runs very stable and on android i am having this problem

"react-native": "0.68.2",
"mixpanel-react-native": "^2.2.5",

Please help me

**Comment by lucyblake2023** [comment]
@zihejia please help me

**Comment by zihejia** [comment]
hi @lucyblake2023 , I'm so sorry, do you still have the problem? Usually, this happens when your test device lost internet access.

**Comment by zihejia** [comment]
Close inactive issues

**Comment by Parmar-Bansi** [comment]
same issue

event called but not shown in mix panel connect data setup or anywhere else
please guide me
