### ISSUE TITLE
Issue with addGroup/setGroup on both platforms

### ISSUE THREAD

**Issue by TheWygoda** [mixpanel/mixpanel-react-native#21]
I've run into problem with addGroup/setGroup

On android mixpanel is unable to set proper distinct id 
<img width="1346" alt="mixpanel issue 0" src="https://user-images.githubusercontent.com/32249347/104743053-89bd9980-574b-11eb-99f0-be67fc22b57b.png">
<img width="392" alt="Zrzut ekranu 2021-01-15 o 15 34 26" src="https://user-images.githubusercontent.com/32249347/104743072-8f1ae400-574b-11eb-9d02-6b35254d4a5a.png">

on the iOS problem is not that big because it's only lacking some less valuable data like region etc 
<img width="361" alt="Zrzut ekranu 2021-01-15 o 16 01 33" src="https://user-images.githubusercontent.com/32249347/104743092-94782e80-574b-11eb-988e-b1f18efe2f16.png">

On my side i've check if all of those values are defined and they are. Also some of those values are collected under **User** and they look fine there.

**Comment by jpacyfik** [comment]
Any chance for response?

**Comment by zihejia** [comment]
hi @TheWygoda @jpacyfik, we will have a look.

**Comment by zihejia** [comment]
Hi @TheWygoda I've fixed the issue in v1.0.2.  I'm closing this issue now, please feel free to reopen it or contact Mixpanel  [support](https://help.mixpanel.com/hc/en-us/requests/new). Once again, thanks for bringing this up.
