### ISSUE TITLE
App version missing after upgrade from 2.1.2 to 2.3.1

### ISSUE THREAD

**Issue by AdamGerthel** [mixpanel/mixpanel-react-native#212]
As the title says. After upgrading our RN project from 2.1.2 to 2.3.1, we're no longer seeing any data for the "App Version" property. As seen in the screenshot below, our latest release is listed under "Not set".

![Screenshot 2023-09-21 at 09 18 14](https://github.com/mixpanel/mixpanel-react-native/assets/1490370/38fa0246-411a-46cd-b941-63e9cc580224)

**Comment by zihejia** [comment]
hi @AdamGerthel , we have fixed this issue in v2.4.1. Closing this one now, please reopen if the problem exists.
