### ISSUE TITLE
underlying Objective-C module 'Mixpanel' not found -xcode 15

### ISSUE THREAD

**Issue by Priyanka-SP** [mixpanel/mixpanel-react-native#213]
Hello I'm having issue with react native app which works fine on older version of xcode(14.2),when I upgraded the xcode its failing with the following errors:
<img width="891" alt="image" src="https://github.com/mixpanel/mixpanel-react-native/assets/61545049/9330b67e-41d2-4e68-92f7-7d94d8d37ab7">

**Comment by JohnathanWhite** [comment]
Also seeing this

**Comment by andev240** [comment]
I am also facing the same issue when I upgraded Xcode to the latest version **(Version 15.0 (15A240d))** Earlier it was working fine,

**Comment by hamzakashifCL** [comment]
Facing the same issue.

is there any update on this?

**Comment by zihejia** [comment]
sorry for the late response. Have you solved the problem? It might be the caching issue: https://github.com/pmadruga/react-native-clean-project

**Comment by harisfasset** [comment]
having the same issue, is there a workaround for this?

**Comment by zihejia** [comment]
hi @harisfasset , clean your project cache might help. If not, have you tried creating an empty project and see how it goes? 
alternatively, you can try turn on the Javascript mode, see the release note: https://github.com/mixpanel/mixpanel-react-native/tree/v3.0.0-beta.1

**Comment by zihejia** [comment]
This issue should not be related to the SDK itself. Also, version 3.0.0 has now been officially released with Javascript mode. Please reopen this if you need further assistance.
