### ISSUE TITLE
Error: mixpanel-react-native: MixpanelReactNative is null.

### ISSUE THREAD

**Issue by helians11** [mixpanel/mixpanel-react-native#214]
Error: mixpanel-react-native: MixpanelReactNative is null.

Still getting this error.
mixpanel-react-native: ^2.3.1
react-native: 0.71.8

import { Mixpanel } from 'mixpanel-react-native';

const mixpanel = new Mixpanel(projectToken, true);

**Comment by elvniv** [comment]
were you able to solve it? i am getting the same error and nothing online is helping 

import { Mixpanel } from 'mixpanel-react-native';
import { MIXPANEL_TOKEN } from './env';

const trackAutomaticEvents = true;

export const mixpanel = new Mixpanel(MIXPANEL_TOKEN, trackAutomaticEvents);

**Comment by helians11** [comment]
Nope... nothing is helping.

**Comment by elvniv** [comment]
its super annoying because they aren't responding either

**Comment by elvniv** [comment]
hey, any luck?

**Comment by OOCAZ** [comment]
same issue, not a clue what is going on, just using boilerplate docs, will see if I can get to the bottom of this quickly.

**Comment by elvniv** [comment]
yeah, switch the product. use the library managed by someone else. they
don't actually have any library that works with expo according to them.

**Comment by OOCAZ** [comment]
@zihejia Any input?

**Comment by OOCAZ** [comment]
To update this issue I found a work around by just importing and using: https://www.npmjs.com/package/mixpanel-browser. However this is not direct react-native support... 

But in the event of a work around just use that according to the guides @elvniv  and @helians11, it should work for you.

**Comment by OOCAZ** [comment]
Adding additional documentation, I tried the last three previous version and those did not work, going to see if I can fork and fix after business hours.

**Comment by elvniv** [comment]
let me see if i can dig up the email mixpanel sent me they gave me a third
party library i could use

**Comment by elvniv** [comment]
here
https://github.com/mixpanel/mixpanel-react-native/issues/82

**Comment by zihejia** [comment]
hi, it seems like you are trying to run it without the Native module, we have just released a beta version, [v3.0.0-beta.1](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v3.0.0-beta.1). This version allows you to enable JavaScript mode when initializing Mixpanel, which should work with your case. For more details and installation guidelines, please refer to the release notes at [Mixpanel React Native v3.0.0-beta.1](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v3.0.0-beta.1). I'm consolidating all the similar issues, please use #82 or open a new one for any feedback or issues in 3.0.0-beta versions 🙏
