### ISSUE TITLE
mixpanel-react-native is not working properly.

### ISSUE THREAD

**Issue by chetan-sharma-newput** [mixpanel/mixpanel-react-native#22]
It's not working properly, it is so slow to update the event on the server, davodesign's mix-panel lib is much faster than this lib. I tried a lot but no luck.

**Comment by zihejia** [comment]
hi @chetan-sharma-newput , to preserve battery life and customer bandwidth, the Mixpanel library doesn't send the events you record immediately. Instead, it sends batches to the Mixpanel servers every 60 seconds while your application is running, as well as when the application transitions to the background. 

You can call flush manually if you want to update the event on the server immediately `mixpanel.flush();` Please let me know if that helps.

**Comment by chetan-sharma-newput** [comment]
> hi @chetan-sharma-newput , to preserve battery life and customer bandwidth, the Mixpanel library doesn't send the events you record immediately. Instead, it sends batches to the Mixpanel servers every 60 seconds while your application is running, as well as when the application transitions to the background.
> 
> You can call flush manually if you want to update the event on the server immediately `mixpanel.flush();` Please let me know if that helps.

Hello zihejia,

I want to track my user's anonymous activity before his login, after login, and after logout. This is what I am doing. and yes "mixpanel.flush()" worked thank you.

```
    registerSuperPropertyMixPanel(option) {
        this.mixpanel.registerSuperProperties(option.properties)
    }

    async registerUserOnMixPanel(peopleData) {
        this.mixpanel.alias(peopleData.uuid, distinctId)
        this.mixpanel.identify(peopleData.uuid)
        // MixPanel.createAlias(peopleData.uuid)
        // MixPanel.identify(distinctId);
        this.mixpanel.getPeople().set(peopleData)
        // MixPanel.setOnce(peopleData)
        this.registerSuperPropertyMixPanel({
            "properties": {
                "app": getConstant().PILOT_NAME,
                "pilotId": getConstant().PILOT_ID,
                "uuid": peopleData.uuid
            }
        })
        this.trackView("app.home")
        this.mixpanel.flush()
    }
```
Now this code creating always a new user profile on mixpanel database. I want to track all the anonymous activity of the user. 

Like - First he comes on the login screen when he launches the app, then he logged in to the app, he does some tasks, and then logs out from the app, now he again logs in.  So this activity I want to track with a single mixpanel user profile. Sorry for the bad English and thanks in advance.

**Comment by zihejia** [comment]
hi @chetan-sharma-newput ,  I could not replicate the same issue. Is your Mixpanel project using Identity Merge? If yes or you are not sure, you can check this doc: https://help.mixpanel.com/hc/en-us/articles/360041039771-Getting-Started-with-Identity-Management. If Id merge is enabled, you don’t need to call `alias`.

If you do not enable Identity Merge. You can check this doc: https://help.mixpanel.com/hc/en-us/articles/115004497803-Identity-Management-Best-Practices. The key here is you only need to call `alias` once when users first sign up. When a user logs in, you can just call `mixpanel.identify("YOUR_USER_ID")`. As long as you keep your user id the same(peopleData.uuid), there shouldn’t be a new user profile being created each time. 

Please let me know if that helps.

**Comment by zihejia** [comment]
hi @chetan-sharma-newput , I'm closing this issue for now as it's not a real issue. Please feel free to open another one for any specific issue or contact Mixpanel [support](https://help.mixpanel.com/hc/en-us/requests/new) .
