### ISSUE TITLE
module map file. Mixpanle.modulemap not found

### ISSUE THREAD

**Issue by hamzakashifCL** [mixpanel/mixpanel-react-native#220]
I am getting this error

/Users/hamzakashif/Library/Developer/Xcode/DerivedData/xyz-esatleubsfjzrnbczbejzvlprcdb/Build/Intermediates.noindex/xyz.build/Debug-iphonesimulator/xyz.build/DerivedSources/xyz.c module map file '/Users/hamzakashif/Desktop/xyz/xyz-mainapp/client/mobile/ios/Pods/Headers/Public/Mixpanel/Mixpanel.modulemap' not found

how to resolve this issue

xcode 15.1
React native 0.73
mixpanel-react-native 2.4.0

**Comment by varun-gadre** [comment]
I just started getting something similar on my side. Used to work great but now there seems to be a problem with the briding header not being able to find `Mixpanel/Mixpanel.h` any ideas what I might be doing differently / wrong?

**Comment by zihejia** [comment]
it seems to be a caching issue, please refer to: https://github.com/pmadruga/react-native-clean-project
I'm closing this one, feel free to reopen if the problem still exists.
