### ISSUE TITLE
IOS "App Crashed" event is not automatically tracked by mixpanel. But the event "App Crashed" in Android is tracked

### ISSUE THREAD

**Issue by varshasunilkumar** [mixpanel/mixpanel-react-native#222]

**Comment by sbarcenascode** [comment]
Same issue but with `AppSession` is not being tracked in IOS.

**Comment by zihejia** [comment]
hi @varshasunilkumar , `App Crashed` is not supported in our iOS. 
@sbarcenascode `App Session` is only triggered when users spend more than 10 seconds in their app. I'm closing this one now, feel free to open a new ticket if you don't see `App Session` ever.
