### ISSUE TITLE
Issues with v3 Version on react-native-web

### ISSUE THREAD

**Issue by upacyxou** [mixpanel/mixpanel-react-native#232]
Hello! It appears that the v3 version of Mixpanel is not functioning properly on the web. When attempting to call the ```init``` method, I encounter the following error: ```MixpanelReactNative is undefined```. Additionally, I encounter an error when trying to call the ```track``` method: ```constants is undefined```. This issue persists even in the provided sample available [here](https://github.com/mixpanel/mixpanel-react-native/tree/master/Samples/MixpanelExpo).
<img width="1312" alt="Screenshot 2024-04-12 at 17 55 27" src="https://github.com/mixpanel/mixpanel-react-native/assets/57546893/6564ce93-6c3d-431b-8540-37a9a7fba7cb">
<img width="1312" alt="Screenshot 2024-04-12 at 17 55 42" src="https://github.com/mixpanel/mixpanel-react-native/assets/57546893/c188fef1-cd54-45ad-842c-e37d860c4f5a">

**Comment by zihejia** [comment]
hi @upacyxou , can you try v3.0.1? sorry for the inconvenience.

**Comment by upacyxou** [comment]
same issue :(

**Comment by zihejia** [comment]
The issue has been fixed in 3.0.2. I'm closing this one now, feel free to reopen if the problem still exists.
