### ISSUE TITLE
Issue with intialisation on v3.0.2

### ISSUE THREAD

**Issue by pratyush0103** [mixpanel/mixpanel-react-native#236]
When I am initializing on web I get this error ->

-- TypeError: Cannot read properties of undefined (reading 'Brand')
    at MixpanelMain.getMetaData (mixpanel-main.js:44:1)
    at MixpanelMain.<anonymous> (mixpanel-main.js:88:1)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    
    I looked into the code and found out that you guys are extracting Constants from Platform
    
    const {OS, Version, constants} = Platform;
    const {Brand, Manufacturer, Model} = constants;
    
    the thing is constants are undefined on web so when we are trying to get Brand from it its throwing an error, 
    A quick fix is initializing constants with an empty obj before initializing mix-panel like this -> 
    
  Platform.constants = {
   Brand: '',
   Manufacturer: '',
   Model: '',
 };
 
 but this needs to be fixed.

**Comment by zihejia** [comment]
@pratyush0103 , thanks for bringing this up. Do you mind open a pull request for it?

**Comment by pratyush0103** [comment]
@zihejia, there you go [https://github.com/mixpanel/mixpanel-react-native/pull/238](url).
