### ISSUE TITLE
Feature request: Support react-native-web

### ISSUE THREAD

**Issue by MikkoSteerpath** [mixpanel/mixpanel-react-native#24]
We build apps for ios, android and web with react-native (and react-native-web).

For FirebaseAnalytics Expo provides a great library that works accross all three platforms https://docs.expo.io/versions/latest/sdk/firebase-analytics/ 

Please consider supporting react-native-web with this library.

**Comment by izakfilmalter** [comment]
Ya I also would like this feature. Having to build an abstraction for web sucks.

**Comment by zihejia** [comment]
As we are gathering feedback for now, if there are more requests, we will definitely consider adding support to it.

**Comment by vj-raghavan** [comment]
Our react native app also needs to support Web which we currently do by Mixpanel-browser and support it by the build process. Would be great to have mixpanel support web using this plugin.

**Comment by ToyboxZach** [comment]
This would be super helpful for us

**Comment by ilyausorov** [comment]
+1 for this request. Currently I also have mixpanel-browser and created an abstraction layer, for the slight differences between the two libraries

**Comment by powerpufffs** [comment]
Just putting in another request for this! That would be huge for us @zihejia

**Comment by jeanniton-mnr** [comment]
+1

I would love to use one MixPanel react-native library for both native and web built.

Thank you !

**Comment by a-tokyo** [comment]
Looking forward to this!

**Comment by zihejia** [comment]
Hello, thank you all for your patience. We have just released a beta version, [v3.0.0-beta.1](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v3.0.0-beta.1), that should work with React Native for Web. For more details and installation guidelines, please refer to the release notes available at [Mixpanel React Native v3.0.0-beta.1](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v3.0.0-beta.1). We welcome you to report any issues or provide feedback! 🙏

**Comment by zihejia** [comment]
Version 3.0.0, which includes support for react-native-web, is now released. I'm closing this thread. Please feel free to raise any issues if they arise.
