### ISSUE TITLE
CORS issue coming on web!

### ISSUE THREAD

**Issue by pratyush0103** [mixpanel/mixpanel-react-native#240]
Hey guys, I am using Expo with react-native-web for developing on the web, the library is working fine on Android and ios, but on the web builds it's giving me a cors error on localhost as well as actual deployment, I am using s3 with Cloudfront CDN to deploy the web version.

**Comment by zihejia** [comment]
hi @pratyush0103 , 3.0.5 should have the fix for it, I'm closing it now but feel free to reopen if the problem still exits.
