### ISSUE TITLE
Mixpanel not working in expo web

### ISSUE THREAD

**Issue by Nkgohil007** [mixpanel/mixpanel-react-native#248]
I am unable to use Mixpanel on the expo web.
I am able to use it in ios and Android devices.

and also the expo sample used in this repo is not working in web too

can anyone please look into this issue?
@zihejia

**Comment by ankitpmi** [comment]
same issue @zihejia

**Comment by Nkgohil007** [comment]
https://github.com/mixpanel/mixpanel-react-native/pull/253
resolved it in this PR

**Comment by zihejia** [comment]
3.0.5 is out and should have fixed the issue. Feel free to reopen if the problem exits.
