### ISSUE TITLE
In iOS I cannot initialize the library

### ISSUE THREAD

**Issue by pixsolution** [mixpanel/mixpanel-react-native#25]
RN version: 0.60.5
Mixpanel RN library: 1.0.1

Hi there! In Android I could do the implementation well everything worked for me following the documentation but in iOS I cannot initialize the library with the function
`configMixpanel = async () => {
       this.mixpanel = await Mixpanel.init("Your mixpanel token");
   }`
in the debug I see that this function returns it undefined 
![Captura de Pantalla 2021-02-01 a la(s) 2 03 57 p  m  (1)](https://user-images.githubusercontent.com/47191848/106499842-6885d880-64c1-11eb-9cce-7e08c1b8904d.png)
what can it be?

I'll appreciate your help
Regards

**Comment by zihejia** [comment]
hi @pixsolution , would you mind providing more sample regarding how you put `configMixpanel`? Also you may want to try our demo app to see if that works for you. https://github.com/mixpanel/mixpanel-react-native/tree/master/MixpanelDemo

**Comment by pixsolution** [comment]
Hello @zihejia  Thanks for your reply, suddenly start working on iOS perfect and now stop working on Android (the strange thing is that it does not show any error) the only think I do was pass from version 1.0.1 to 1.0.2. I think it's a problem with library thats no sending the events to Mixpanel. If It was my code never work or show an error...

**Comment by zihejia** [comment]
hi @pixsolution , If iOS is working fine, in that case, I will close this one and let's use this issue to track instead. https://github.com/mixpanel/mixpanel-react-native/issues/27
