### ISSUE TITLE
Support expo managed workflow

### ISSUE THREAD

**Issue by dacevedo12** [mixpanel/mixpanel-react-native#26]
It would be great for this library to support simpler features for JS-only RN apps

**Comment by dacevedo12** [comment]
Here are some non-official and somewhat outdated alternatives:

- https://www.npmjs.com/package/expo-mixpanel-analytics
- https://www.npmjs.com/package/@bothrs/expo-mixpanel-analytics

**Comment by zihejia** [comment]
hi @dacevedo12 , thanks for the feedback. We will consider adding it if there are many similar requests.

**Comment by zihejia** [comment]
Hi @dacevedo12 , let's use this one to track: https://github.com/mixpanel/mixpanel-react-native/issues/24. I'm closing this one now.
