### ISSUE TITLE
Events Not Showing up in Dashboard Android - Expo Ejected Project

### ISSUE THREAD

**Issue by pranav1605** [mixpanel/mixpanel-react-native#27]

**Comment by subinsuresh** [comment]
Same happening to me as well. But I am using CLI instead of Expo. Debugging logs shows events are posted successfully when turned on from android manifest file.

**Comment by zihejia** [comment]
hi @subinsuresh @pranav1605 , sorry for the late response. Do you still have the problem? 

Have you tried calling `mixpanel.flush();`? To preserve battery life and customer bandwidth, the Mixpanel library doesn't send the events you record immediately. Instead, it sends batches to the Mixpanel servers every 60 seconds while your application is running, as well as when the application transitions to the background.  You can call flush manually if you want to force a flush at a particular moment.

**Comment by zihejia** [comment]
I'm closing this issue now, please feel free to reopen if the problem still exists.
