### ISSUE TITLE
SIGABRT Crash on iOS 

### ISSUE THREAD

**Issue by ramakula** [mixpanel/mixpanel-react-native#272]
We are seeing a huge spike in Mixpanel crashes, we are currently on version 3.0.5:

"mixpanel-react-native": "^3.0.5",

Stacktrace:

SIGABRT

ibsqlite3.dylib +0x9b3c        0x1b21dcb3c (0x1b21dc6e4 + 1112)
1  <unknown> +0xf84afa81b8c84ac4   0xf84afa81b8c84ac4
2  libsqlite3.dylib +0x9154        0x1b21dc154 (0x1b21dbebc + 664)
3  libsqlite3.dylib +0x8d2c        0x1b21dbd2c (0x1b21dbc50 + 220)
4  XXXXX +0x1870d8              closure #1 in MPDB.insertRow(_:data:flag:) (MPDB.swift:165:24)
5  XXXX +0x186fb8              MPDB.insertRow(_:data:flag:) (MPDB.swift)
6  XXXXX +0x18da24              Track.track(event:properties:timedEvents:superProperties:mixpanelIdentity:epochInterval:) (MixpanelPersistence.swift:73:18)
7  XXXXX +0x177414              closure #1 in MixpanelInstance.track(event:properties:) (MixpanelInstance.swift:1056:58)
8  XXXX +0x6f360               thunk for @escaping @callee_guaranteed @Sendable () -> () (<compiler-generated>)
9  libdispatch.dylib +0x2138       __dispatch_call_block_and_release
10 libdispatch.dylib +0x3dd0       __dispatch_client_callout
11 libdispatch.dylib +0xb3fc       __dispatch_lane_serial_drain
12 libdispatch.dylib +0xbf60       __dispatch_lane_invoke
13 libdispatch.dylib +0x16cb0      __dispatch_root_queue_drain_deferred_wlh
14 libdispatch.dylib +0x16524      __dispatch_workloop_worker_thread
15 libsystem_pthread.dylib +0x4930 __pthread_wqthread

It looks like there is a deadlock somewhere in your native SDK.

Would this be fixed in we upgrade to 3.0.7? It looks like no based on changelog. When can we expect a response?

**Comment by ramakula** [comment]
It looks like your native SDK uses ReadWriteLock. It is known for these kind of deadlocks. Most people have moved to Using DispatchQueue with .concurrent/Sendable closures etc.

**Comment by jaredmixpanel** [comment]
@ramakula The `ReadWriteLock` class in `mixpanel-swift` already uses `DispatchQueue` with `.concurrent`: https://github.com/mixpanel/mixpanel-swift/blob/master/Sources/ReadWriteLock.swift

 You said you're seeing a huge spike, any idea what recent changes may have led to the spike? 

Can you reproduce the crash?

Are you possibly instantiating multiple instances of the Mixpanel SDK?

**Comment by ramakula** [comment]
Ah I see, we have not changed anything on our side. We are unable to reproduce but it seems to be happening on the latest versions on OS:

![Image](https://github.com/user-attachments/assets/d5ed611c-3dac-40e3-91ad-0112e336a570)

We have not changed anything on the app side of the things for a few months now.

**Comment by jaredmixpanel** [comment]
Hmm, it's been several years since there were any changes to the concurrency mechanisms or the database of `mixpanel-swift` and this is the only report of this kind we have and nothing is jumping out at me after a quick review of changes in the latest iOS versions so I'm not sure what might have triggered this spike.

- [ ] Are you instantiating multiple instances of the Mixpanel SDK? 
- [ ] Are you tracking from multiple threads?
- [ ] Any server-side changes that might have impacted client-side behavior?
- [ ] Do you have any other stack traces, details or context that might help?

**Comment by ramakula** [comment]
I've triple checked everything. Nothing has changed in terms of initialization in the past 3 months on out side. Definitely not doing multiple threads. We don't rely on server side for initialization flow.  We were on 3.0.5, we will upgrade to the latest (3.0.7) in the next release. Crashes are a bit all over the place so I'm unable to get the exact context. Will keep you posted.

**Comment by ramakula** [comment]
We have identified the root cause to be something else within our app. It was due to some other uncaught exceptions. I'm closing this as a non-issue.  Thank you @jaredmixpanel for all the help.
