### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSString

### ISSUE THREAD

**Issue by MyRealFood** [mixpanel/mixpanel-react-native#32]
Hi there!

I am using the latest version of mixpanel-react-native "^1.1.0" using react "16.13.1" and react-native "0.61.5"
and when I try to initialize the Mixpanel library using the following code

this.mixpanel = await Mixpanel.init("*************");

I received the following error screen on iOS devices:
![__](https://user-images.githubusercontent.com/67127474/110012757-27cbea00-7d21-11eb-81fd-a1ac77ebfc59.png)

**Comment by zihejia** [comment]
hi @MyRealFood , could you share more code for how you initialize it?  How you put this line `this.mixpanel = await Mixpanel.init("*************");`

**Comment by MyRealFood** [comment]
Hi there!

I have created a method that I call at the startup of my app called onAppLaunched as shown:

```
async onAppLaunched() {
      this.mixpanel = await Mixpanel.init("***************************");
}
```

This method is called by my Navigation controller (I use Wix Navigation) inside the method registerAppLaunchedListener:

```
Navigation.events().registerAppLaunchedListener(() => {
  ...
  Analytics.onAppLaunched();
  ...
}
```

At the moment of call the method, the error is thrown.

**Comment by zihejia** [comment]
hi @MyRealFood , do you mind attaching a small sample app? I'm still having trouble replicating the issue.

**Comment by zihejia** [comment]
I'm closing this for now due to inactivity. Please feel to reopen or contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues.
