### ISSUE TITLE
Crash between older setups and this lib because of swift.

### ISSUE THREAD

**Issue by vongohren** [mixpanel/mixpanel-react-native#33]
I have been in contact with customer support, and community regarding this error. See following communication for details.
Here is my comment on the initial community error: https://community.mixpanel.com/strategy-and-planning-9/swift-errors-in-react-native-library-5071?postid=7616#post7616

And here is the email with support: [Diwala Mail - [Mixpanel] Re_ React native library does not work on iOS.pdf](https://github.com/mixpanel/mixpanel-react-native/files/6116799/Diwala.Mail.-.Mixpanel.Re_.React.native.library.does.not.work.on.iOS.pdf)

What basically lead me to fixing this, was this comment: https://github.com/facebook/react-native-fbsdk/issues/755#issuecomment-653043458

I dont know why it is happening on this lib? Guess it is in swift and there is a crash there?
Maybe its worth documenting?

I just atleast wanted to highlight this and showcase the fix that worked for me.

**Comment by zihejia** [comment]
Hi @vongohren , thank you so much for bringing it up and providing the solution. It's valuable to anyone who has the same issue.

**Comment by bobhuangab** [comment]
after we enable swift, ipa size become huge @vongohren

**Comment by vongohren** [comment]
@bobhuangab I have not analyzed that on our end, so I guess @zihejia has to give some feedback on that. Why they depend on swift and is not backward compatible
