### ISSUE TITLE
Events no longer show up on Android if I use the EU data servers

### ISSUE THREAD

**Issue by matt-dalton** [mixpanel/mixpanel-react-native#37]
I tried following [these instructions](https://developer.mixpanel.com/docs/react-native#eu-data-residency) to get the events to send to the EU servers instead of the default. Now I can no longer see events appearing in Live View.

Is this functionality definitely working? Or is there something I need to do to see these in the Live View feed?

**Comment by zihejia** [comment]
hi @matt-dalton , if you are sending to eu, did you look up the Live View in [eu.mixpanel.com](eu.mixpanel.com) instead of mixpanel.com?

**Comment by zihejia** [comment]
hi @matt-dalton , I'm closing this one now. Please feel free to reopen if the problem still exists.
