### ISSUE TITLE
iOS Project Doesnt Build after including the mixpanel package. 

### ISSUE THREAD

**Issue by vj-raghavan** [mixpanel/mixpanel-react-native#38]
Hi All,

I have followed all the instructions provided in the document. We were previously using https://github.com/davodesign84/react-native-mixpanel for tracking events from our react native application.

Now that we have official support from Mixpanel, we have decided to update our application to use this package. However we ran into the following issues after including it on the app. 

iOS app build fails with the following errors,

`❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▸ Compiling AnyTweak.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ApplicationStateSerializer.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling AutomaticEvents.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling AutomaticProperties.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling BaseNotificationViewController.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling BaseWebSocketMessage.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling BindingMessage.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling CGAffineTransformToNSDictionary.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling CGPointToNSDictionary.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling CGRectToNSDictionary.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling CGSizeToNSDictionary.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ChangeMessage.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ClearMessage.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Clip.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Codeless.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling CodelessBinding.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ConnectIntegrations.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Constants.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Decide.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling DecideRequest.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling DeviceInfoMessage.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling DisconnectMessage.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling DisplayTrigger.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Error.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling FileLogging.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Flush.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling FlushRequest.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Group.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling IdentityTransformer.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling InAppButton.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling InAppNotification.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling InAppNotifications.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling JSONHandler.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Logger.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling MD5.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling MiniNotification.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling MiniNotificationViewController.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Mixpanel.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling MixpanelInstance.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling MixpanelNotificationServiceExtension.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling MixpanelType.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Network.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling NSAttributedStringToNSDictionary.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ObjectFilter.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ObjectIdentityProvider.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ObjectSelector.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ObjectSerializer.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ObjectSerializerConfig.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ObjectSerializerContext.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling People.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Persistence.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling PrintLogging.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling PushNotifications.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling ReadWriteLock.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling SelectorEvaluator.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling SessionMetadata.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling SHA256.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling SnapshotMessage.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling SSLSecurity.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Swizzle.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TakeoverNotification.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TakeoverNotificationViewController.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Track.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Tweak.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakableType.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakBinding.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakClusterType.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakCollection.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakGroup.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakLibrary.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakMessage.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakPersistency.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakStore.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling TweakViewData.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling UIColorToNSString.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling UIControlBinding.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling UIEdgeInsetsToNSDictionary.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling UIFontToNSDictionary.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling UIImageToNSDictionary.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling UITableViewBinding.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling UIViewSelectors.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling Variant.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling VariantAction.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling VariantTweak.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling WebSocket.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
       ^

▸ Compiling WebSocketWrapper.swift

❌  /Users<<redacted>>/ios/Pods/Headers/Public/Mixpanel/Mixpanel-swift.modulemap:1:8: redefinition of module 'Mixpanel'

module Mixpanel {
`

**Comment by zihejia** [comment]
hi @vj-raghavan , have you tried doing a clean build?  delete your pod folder, clear all pod caches, build caches and rerun pod install, code build, etc.

**Comment by vj-raghavan** [comment]
Hi Zihe,

I have tried everything from clearing the pods, clearing node modules, reinstalling the modules, build caches etc. 

If it helps the react native project I use 0.61.5 version.  

Thanks
Vijay

**Comment by zihejia** [comment]
hi @vj-raghavan , it must be the cache cause you previously used `react-native-mixpanel`.   This means there are two modulemap files present. You might try to create a new project to see if the problem is still there.

**Comment by vj-raghavan** [comment]
Hi @zihejia I have tried the resolution of clearing all the caches i.e npm cache, node modules, pods, pod cache etc.
I ran into another issue of missing 

> symbol(s) not found for architecture x86_64

For resolving this issue I had to follow the steps in this link https://github.com/facebookarchive/react-native-fbsdk/issues/755#issuecomment-653043458 

> open XCode
create new file, select swift file
confirm "Create Bridging Header"
clean and build (I actually made my first build from XCode and then from react-native CLI)

I have named my swift file 'File.swift' 

Thanks for your help on this and hopefully this helps others who have similar build issues.

**Comment by bobhuangab** [comment]
after "Create Bridging Header"
anyone checked size of ipa size?
Seems my ipa size is trippled

**Comment by vj-raghavan** [comment]
@bobhuangab somethings seems amiss on your builds.. My builds haven't tripled in size. There was a minor increase of 1MB in the total size of the binary.
