### ISSUE TITLE
Looks like on iOS Bluetooth Enabled is always false

### ISSUE THREAD

**Issue by MikkoSteerpath** [mixpanel/mixpanel-react-native#39]

**Comment by zihejia** [comment]
hi @MikkoSteerpath , unfortunately, we don't track this in iOS automatically, only in Android. As a workaround, you have to track it manually, sorry for the inconvenience.

**Comment by zihejia** [comment]
For all the supported default properties collected by properties: https://help.mixpanel.com/hc/en-us/articles/115004613766-Default-Properties-Collected-by-Mixpanel
