### ISSUE TITLE
Where do logs go?

### ISSUE THREAD

**Issue by dansimau** [mixpanel/mixpanel-react-native#41]
Hi there,

I followed the instructions here to enable logging:
https://developer.mixpanel.com/docs/react-native#debugging-and-logging

However, I don't see any logs. I've checked:

* React Native console
* Debug -> Open system.log (iOS Simulator)

But I don't see anything from mixpanel. Am I looking in the wrong place?

**Comment by zihejia** [comment]
hi @dansimau , you can either open your iOS project by using Xcode and the log will be displayed in the Xcode console. Or you can open the console and find your simulator or device there. https://developer.apple.com/documentation/os/logging/viewing_log_messages.

I'm closing this one now, please feel free to reopen if this does not answer your question. Thanks!
