### ISSUE TITLE
App build fails on iOS 14.5

### ISSUE THREAD

**Issue by cigaciga** [mixpanel/mixpanel-react-native#43]
I'm having an issue after upgrading to Xcode 12.5 and iOS 14.5, build is failing with error:

Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libMixpanel-swift.a(AutomaticProperties.o)
ld: symbol(s) not found for architecture x86_64

**Comment by taschik** [comment]
We discovered the same here, too.

**Comment by AndreasGS** [comment]
+1. Disabled mixpanel until it's fixed

**Comment by VincentQuillien** [comment]
same here

**Comment by zihejia** [comment]
Sorry guys! We are looking into this now.

**Comment by mavarazy** [comment]
+1

**Comment by kkelley-leftbrain** [comment]
Hey all - there appears to be some workarounds for 0.64 and at least in my case, 0.63.3 found in the thread mentioned above. My solution was pulled from a lot of folks across a few issues, found [here](https://github.com/facebook/react-native/issues/31179#issuecomment-829568297).

@zihejia not sure if this is potentially the solution here, as a lot of the pain is coming from the Big-Sur automatic updates jacking with XCode and a cascading number of libraries coupled with it. Always appreciate the work you guys are doing, thank you for the support

Cheers

**Comment by zihejia** [comment]
Thanks @kkelley-leftbrain and everyone who brought this up and provided the valuable information. Here is the workaround based on the threads. Tested in Xcode 12.5 and RN 0.64
- open the iOS project/workspace project file
- go to the `Build Settings` of your build target, search for `Library Search Paths`
- remove `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)`
![image](https://user-images.githubusercontent.com/36679208/116619072-d68d4080-a8f4-11eb-8e56-c0c24e9ad5de.png)

- add an empty swift file to your iOS target and create the Bridging Header when prompt
![image](https://user-images.githubusercontent.com/36679208/116619084-dc832180-a8f4-11eb-9e80-7fb610a53767.png)

**Comment by zihejia** [comment]
Feel free to reopen if the above solution doesn't work, or contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues.

**Comment by checklist** [comment]
> Thanks @kkelley-leftbrain and everyone who brought this up and provided the valuable information. Here is the workaround based on the threads. Tested in Xcode 12.5 and RN 0.64
> 
> * open the iOS project/workspace project file
> * go to the `Build Settings` of your project, search for `Library Search Paths`
> * remove `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)`
>   ![image](https://user-images.githubusercontent.com/36679208/116619072-d68d4080-a8f4-11eb-8e56-c0c24e9ad5de.png)
> * add an empty swift file to your iOS target and create the Bridging Header when prompt
>   ![image](https://user-images.githubusercontent.com/36679208/116619084-dc832180-a8f4-11eb-9e80-7fb610a53767.png)

Guys - this has been open since April. It is now August. Shouldn't have this been handled without this extra work?

Thanks in advance.

**Comment by jckw** [comment]
Should this issue be closed? There might be a work around but this doesn't feel fully solved. Do we know why the workaround works (and what does removing the library path do?)?

**Comment by IdrisHanafi** [comment]
bump

**Comment by ekram21** [comment]
I Couldn't find the $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME) in my Library Search Paths either. If this doesnt get resolved soon I may have to look for alternative to mixpanel.

Any ETA when will be resolved? @zihejia

**Comment by zihejia** [comment]
hi @ekram21 @IdrisHanafi , would you like to check out the latest [issue](https://github.com/facebook/react-native/issues/31480) from RN about this? Unfortunately, this issue has still not been fully resolved and a workaround is still needed. It is not specific to Mixpanel but more related to RN with Xcode.

**Comment by mikehardy** [comment]
Coming over here from the related react-native issue, we've worked on this for the next release (0.66) of react-native and have implemented the required workarounds in a general way. This affects *everyone* using react-native so if you can please spread the word to other developers in any other repos you work in to help them out, pointing that related issue and encouraging them to examine the Podfile addition that helps people https://react-native-community.github.io/upgrade-helper/?from=0.65.1&to=0.66.0-rc.4 (check the Podfile workaround line that was added)

**Comment by ololoepepe** [comment]
@zihejia So you say this is RN and Xcode issue, then how could it be that my project compiled fine with the same RN and Xcode versions until installing Mixpanel? The issue still exists and there is no workaround (at least for Xcode 12.5.1). The methods posted above does not work (at least for my case), as I do not have `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)` path nor does the fix from https://github.com/facebook/react-native/issues/31480 help.

**Comment by ololoepepe** [comment]
@mikehardy Well, I have more than 60 native modules and some code in `AppDelegate.m` (if that counts). Surely I have faced some issues from time to time, but none was without a fix/workaround and developers saying "this is not our fault, we will not do anything to fix it".
As for upgrading RN version (mine is 0.64.2), it is hard or even impossible to just upgrade without breaking some package. I know one should upgrade from time to time, but doing it too often is a pain and waste of empolyer's money (especially when some packages breaks and one have to fix them).

**Comment by ololoepepe** [comment]
RN 0.66 gives the same error, by the way.

**Comment by mikehardy** [comment]
I have lots of caching so npx react-native-clean-project was needed in my case as well then pod reinstall and I blew away my ccache for good measure.

**Comment by ololoepepe** [comment]
I've tried react-native-clean-project with exact same results. I have never made any extra changes to xcode/Podfile/whatever-ios-build-related after `create-react-native-app my-project`, so it's as common and default as possible.

And once again, as for blindly upgrading to the next version of RN, there are issues with other packages (at least appropriate react-native-reanimated release seems to be buggy and causes crashes). You may say again "this is 3rd-party persons who causes this", but wait, again, we all live the same world, and `react-native-reanimated` is used more often than `mixpanel-react-native`.

**Comment by ololoepepe** [comment]
@mikehardy 
>Just to make sure I did this: it worked

- Doctor, I've broken my leg.
- Can not reproduce, I also have a leg and it's just fine.

**Comment by LucasGarcez** [comment]
I have the same problem. The only way that works for me was to update macOS to Monterey 12.1, so update Xcode to 13.2.1.  No need for other steps, install lib and pods normally.
My project use` react-native` 0.64.0 and `mixpanel-react-native` 1.3.4

**Comment by zihejia** [comment]
Thanks @LucasGarcez  for pointing it out. Yes, for anyone who has been impacted please update Xcode to 13.2.1 as long as you can, so there is no need for any extra steps mentioned in this thread. Thanks for everyone's great input and sorry for the inconvenience, special thanks to @kkelley-leftbrain @mikehardy and @LucasGarcez !

**Comment by dnlPacheco** [comment]
I'm having a problem similar to this error "Undefined symbols for architecture x86_64". Build is failing with this error:

```
Undefined symbols for architecture x86_64:
 "_RCTRegisterModule", referenced from:
   _initialize_MixpanelReactNative in MixpanelReactNative-7b8382e86c4871ddf502e2111c31c78a0bf98ae8fe355805573d3bbbc4a2d3d1.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried to build in 2 different Mac's:

- Big Sur 11.6.2 - Xcode 12.5
- Catalina 10.15.7 - Xcode 12.4

It's the same project using "react-native: 0.63.4" and "mixpanel-react-native": 1.3.7".

After reading this comment in this issue: 
https://github.com/facebook/react-native/issues/29633#issuecomment-694187116. 

I changed the `s.dependency` to `React-Core` in `MixpanelReactNative.podspec` and the app build successfully.

**Comment by ololoepepe** [comment]
So finally there **is** an issue in this lib (incorrect dependency). Not a big surprise though.

**Comment by princefishthrower** [comment]
@dnlPacheco @wgley3 , even after doing this modification and running `pod update` in my `ios/` folder, I'm still having troubles. Are there any other steps you may have forgot to mention here? 

I'm also worried about the brittleness of this solution, won't the `MixpanelReactNative.podspec` file get overwritten every time we upgrade `mixpanel`?

@mikehardy - I see the podfile modification you mentioned, it's called `__apply_Xcode_12_5_M1_post_install_workaround(installer)` - does this only help M1 macs or will it also help macs in general?

BTW I am on react-native 0.67.2, so I'm not sure how I ran into this issue 😅  (my guess is that my podfile wasn't touched by past upgrade commands because we have so much custom tooling)

**Comment by mikehardy** [comment]
the `__apply_Xcode_12_5_M1_post_install_workaround(installer)` workaround is more of a "12.5+ *or* M1" workaround, it fixes issues with both, and is modified over time in new react-native versions to only be what's currently required. 
You can see it's history here https://github.com/facebook/react-native/blame/main/scripts/react_native_pods.rb#L564-L591

Not sure if you need to, but If you need to patch a podspec, patch-package is your friend https://github.com/ds300/patch-package/ - it will warn you when patches don't apply or versions change so it's not that brittle as it is more "fail fast" as you update. I use it all the time personally.

**Comment by paprikka** [comment]
Hi there! Am I correct to think that https://github.com/mixpanel/mixpanel-react-native/pull/150 would fix the issue mentioned by @dnlPacheco ?

**Comment by paprikka** [comment]
I'm on RN 0.68.x, Xcode 13.4. Here's what worked:

1. fork this repo
2. update the podspec file with the patch mentioned in #150 
3. use the package from GH
    ```diff
    // in package.json
    - "mixpanel-react-native": "^1.4.2",
    + "mixpanel-react-native": "git+ssh://git@github.com/<your org name>/mixpanel-react-native.git",  
    ```
4. clean your pods and reinstall all dependencies `$ yarn`, then `$ arch -x86_64 pod install --repo-update`
5. subscribe to notifications for this repo, so you can drop the fork once it gets updated 🚀💰

**Comment by hamzakashifCL** [comment]
I am still getting this error with REact Native 0.73 and xcode 15.1
