### ISSUE TITLE
Since xcode 12.5, project can't run with debug build configuration with mixpanel. Workaround does not work

### ISSUE THREAD

**Issue by desca595** [mixpanel/mixpanel-react-native#45]
Dear Mixpanel 

I am contacting you because since the last xcode update (12.5), our project can't run in debug mode on iOS because of mixpanel.

To be sure the issue is not within our project, i created a fresh react-native project and installed ONLY mixpanel, nothing else and we are still getting the same issue. Steps to reproduce

1. npx react-native init mixpanelCrashTesting
2. cd mixpanelCrashTesting
3. yarn start
4. npx react-native run-ios (to verify that it runs without any problem, yet, it does)
5. npm install mixpanel-react-native
6. cd ios && pod install
7. cd .. && npx react-native run-ios

result is -> ** BUILD FAILED ** 

if i try to run from xcode, i get more info but that's still not enough to find out 
how to fix this. 

Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libMixpanel-swift.a(AutomaticProperties.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

If i change the build confguration to RELEASE, no problem. But we can't develop effectively like
that, we need a DEBUG config. And to remove & add mixpanel every time we need to debug or release
that's a real pain as a workaround. Every help is appreciated. Thank you in advance

We also tried the workaround you suggested:
-remove $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
- add empty swift like and accept to create bridging header

still did not solve the issue

**Comment by zihejia** [comment]
hi @desca595 , the work around should work on the debug build. Which RN version are you using?

**Comment by desca595** [comment]
hi @zihejia , 

Thanks for your answer. It turned out that you are right and the workaround works. We just looked for it in a bad location. 

We checked the Build Settings in a **COMBINED** mode, and then it's not visible. I just switched the tab to **Levels**, and then we saw the line in your doc : $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)

I could also find this line when i searched for it in our project, so it could be removed even without using xcode.

You can close the issue, everything is fine now.

**Comment by zihejia** [comment]
Thanks @desca595 for sharing this. I'm closing it now.
