### ISSUE TITLE
why is firebase-messaging listed as a dependency? 

### ISSUE THREAD

**Issue by LonelyCpp** [mixpanel/mixpanel-react-native#55]
I couldn't find usages for this dependency : 
https://github.com/mixpanel/mixpanel-react-native/blob/6c8747b4d0f656424970ef595e92421e0b849205/android/build.gradle#L38

If it is essential, there should be a way to override the version with a `project.ext`([example](https://github.com/zo0r/react-native-push-notification/blob/624dd152fa06471e16d3e157aa4f058fe0a01467/android/build.gradle#L58)) variable. `v17.3.4` is quite old.

**Comment by zihejia** [comment]
hi @LonelyCpp , it's obsolete and has been removed in v1.2.3. Thanks for bringing it up!
