### ISSUE TITLE
Getting error while Pod Install: None of your spec sources contain a spec satisfying the dependency: `Mixpanel-swift (= 2.9.3)`.

### ISSUE THREAD

**Issue by rohitatcoffee** [mixpanel/mixpanel-react-native#57]
[!] CocoaPods could not find compatible versions for pod "Mixpanel-swift":
  In Podfile:
    MixpanelReactNative (from `../node_modules/mixpanel-react-native`) was resolved to 1.2.2, which depends on
      Mixpanel-swift (= 2.9.3)

None of your spec sources contain a spec satisfying the dependency: `Mixpanel-swift (= 2.9.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by zihejia** [comment]
hi @rohitatcoffee , your cocoa repo is out of date. If you run `pod repo update` or `pod install --repo-update`, that should be able to fix it.

**Comment by zihejia** [comment]
hi @rohitatcoffee , I'm closing this one now, please free to reopen if needed.
