### ISSUE TITLE
React native Mixpanel-react-native errors

### ISSUE THREAD

**Issue by ArmyDev** [mixpanel/mixpanel-react-native#58]
With the last update of macOS 11.3.1 and Xcode 12.5 me and my Colleagues are not able to run our react native apps with mixpanel-react-native dependency. Each time we try to compile and run the app it gives us an error like this:

** BUILD FAILED **

The following build commands failed:
        Ld /Users/armandasastrauskas/Library/Developer/Xcode/DerivedData/AwesomeProject-dyoeqkcqjyqzweaytzdetoekvcmk/Build/Products/Debug-iphonesimulator/AwesomeProject.app/AwesomeProject normal
(1 failure)

**Comment by zihejia** [comment]
hi @ArmyDev , It's a known issue, workaround is here: https://github.com/mixpanel/mixpanel-react-native/issues/43#issuecomment-829599732. I'm closing this one now, please feel free to reopen if the problem still exists.
