### ISSUE TITLE
Tracking and Identifying Oh My!

### ISSUE THREAD

**Issue by eladgel** [mixpanel/mixpanel-react-native#60]
I am confused!
I have read this: https://help.mixpanel.com/hc/en-us/articles/115004497803-Identity-Management-Best-Practices
And I'm trying to understand something:
I have a user that is using the app for the first time(or logged out)
I'm assuming from the docs that when they started the app, they receive a uniques identifier that is being used to send events

1. If they tap login- easy peasy I'm login them in and call identify -done we know who the user is
2. If they register, I should call **mixpanel.alias("some_user", user.id)**. **Why not call here identify?** 
3. Then upon login after register i need to call identify? **What if on my app upon registration completion, the user is logged in?** Should the process then be: **alias()** ------> and then **identify()** immediately?  **This is not coherent from the docs**

Thanks in a advance

**Comment by zihejia** [comment]
Hi @eladgel , I'm so sorry for the late response. 

If you enable Mixpanel ID Merge, just call identify with your chosen identifier as soon as you know who the user is to merge anonymous and identified distinct_ids.  Calling `alias` on sign up is no longer required. Here is the doc on how to enable ID Merge. https://help.mixpanel.com/hc/en-us/articles/360039133851-Moving-to-Identity-Merge

Previously before ID Merge introduced, Mixpanel could only map pre-sign up activity back to a user who was later identified by calling `alias`. Any activity a user did anonymously before signing in again could not be attributed to that user without calling `alias`. In the old system, what you described in no.3 is correct. The key is `register`= `alias`(should only be called once) and `login` = `identify`

I'm closing it now but please feel to continue the conversion if needed.
