### ISSUE TITLE
A lot of "undefined symbol" errors happening with the latest version

### ISSUE THREAD

**Issue by phatlaunchdeck** [mixpanel/mixpanel-react-native#64]
Hello, I have just integrated the latest version of this library into our RN app (0.63.4) and this keeps happening (all installation and pod install steps were taken properly):
![Screen Shot 2021-06-17 at 05 05 04](https://user-images.githubusercontent.com/37071140/122300683-d4755480-cf29-11eb-8704-dcdbcfd051b4.png)

I don't know if this issue is related to the one mentioned in the workaround or not, but I have tried that one regardless (removed Swift 5 line and added the bridging header) but the same errors persisted, any help would be very much appreciated!

**Comment by zihejia** [comment]
hi @phatlaunchdeck , which Xcode version are you on? Did you create the empty swift file?

**Comment by phatlaunchdeck** [comment]
@zihejia I'm on XCode 12.5 and yes, added the empty file so that it prompted me to create the bridging header.

**Comment by AlvaroMorales628** [comment]
Hello, I am also experiencing the same error. I'm on Xcode version 12.5, React Native 0.63.3, and have already created the empty swift file and bridging header. Any help on the matter would be appreciated.

**Comment by phatlaunchdeck** [comment]
@zihejia Any idea on this? As it seems like that I'm not the only one encountered.

**Comment by zihejia** [comment]
hi @phatlaunchdeck and @AlvaroMorales628 , I have a hard time replicating the problem. Removing the Swift 5 line and adding the bridging header should be enough to fix the swift compile issue.  Have you tried a clean build? You can use this command-line tool https://www.npmjs.com/package/react-native-clean-project.  If it's still not working, any chance you can upgrade to 0.64.2? 

If it's possible, are you able to create a minimum sample project and attach it to this thread to demonstrate the issue?

**Comment by phatlaunchdeck** [comment]
@AlvaroMorales628 I just managed to successfully build out the project without having to upgrade to RN 0.64. The catch was that I was having the line `pod 'Mixpanel'` inside my Podfile, removing it did the trick.

@zihejia Maybe this should be noted on the README as well? As I know that a lot of people still thinking that they need to manually update their pod file.

**Comment by zihejia** [comment]
hi @phatlaunchdeck , that's great news. I will do it.
