### ISSUE TITLE
Xcode 12.5.1 linking issue

### ISSUE THREAD

**Issue by branislavantic87** [mixpanel/mixpanel-react-native#68]
After updating Xcode to latest version, project is unable to build there is some issue in this file libMixpanel-swift.a.

generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libMixpanel-swift.a(AutomaticProperties.o)

**Comment by zihejia** [comment]
Hi @branislavantic87 , please refer to this https://github.com/mixpanel/mixpanel-react-native/issues/43#issuecomment-829599732
