### ISSUE TITLE
Are the documented initializations correct?

### ISSUE THREAD

**Issue by tncbbthositg** [mixpanel/mixpanel-react-native#70]
I'm not positive that the readme or the demo application are initializing the Mixpanel instance safely.

For example, in the readme, this is the intended approach for initializing the Mixpanel instance:

```javascript
import { Mixpanel } from 'mixpanel-react-native';
...
class YourClass extends React.Component {
    constructor(props) {
        super(props);
        this.configMixpanel();
    }

    configMixpanel = async () => {
        this.mixpanel = await Mixpanel.init("Your mixpanel token");
    }
...
```

I think that async initialization is generally frowned upon in constructors because you can't reasonably make predictions about the behavior.  In this case, it's possible that someone could try to access `this.mixpanel` before it has been assigned, right?

Often, if something has to be done asynchronously in React, it'll be handled in `componentDidMount` rather than in the constructor.  I know this isn't "loading" or "initializing" really, but it smells kind of funny.  

I think that's probably partially why the `MixpanelManager` class was created in the demo project.  But, this also has async work in the constructor:

```javascript
export default class MixpanelManager {
    static sharedInstance = MixpanelManager.sharedInstance || new MixpanelManager();

    constructor() {
        this.configMixpanel();
    }
    
    configMixpanel = async () => {
        this.mixpanel = await Mixpanel.init(MixpanelToken);
    }
}
```

It seems like there are two potential issues with this.  One of them is that it hides the fact that there's async work being done from the consumer.  The other is that there's not a good way for the consumer to wait for initialization before continuing.

Indeed, this code results in an error:

```javascript
import { MixpanelManager } from './MixpanelManager';

MixpanelManager.sharedInstance.mixpanel.track("Race lost. :(");  // undefined is not an object
```

It totally makes sense that this kind of thing would pop up.  A lot of analytics libraries manage their own singletons.  They have an async init method you can `await`, but the singleton is always accessible.  In this case, we manage our own Mixpanel instance and we have to get it asynchronously because it constructs and initializes at the same time.

I guess, all of this is to say, are these examples appropriate as the canonical examples of how to consume this library?

**Comment by dipalinjawale** [comment]
Any progress on above issue? I am facing same error for initialization.
TypeError: this.mixpanel.track is not a function. (In 'this.mixpanel.track('my message')', 'this.mixpanel.track' is undefined)

**Comment by zihejia** [comment]
@tncbbthositg Thanks for bringing it up. We will fix this.

**Comment by tncbbthositg** [comment]
@dipalinjawale, there are a few ways I considered handling this.  Typically, with an async init, you'll get a promise you can await, but that's kind of hidden in the docs.  With stateless functional components and hooks, maybe you could use state with a lazy initializer?  Something like this would probably work:

```typescript
const mixpanel = useState(() => Mixpanel.init("Your mixpanel token"));

// ...

const onSomeEvent = async () => {
  // do important things
  (await mixpanel).logEvent("my event");
}
```

I have an analytics "service" to abstract the logging (so I can easily switch logging services . . . which I did recently to adopt mixpanel).

So, I have a `lazy` function that effectively memoizes a promise.  Memoization libraries do this really well . . . but I didn't feel like adding an entire library for this problem so here's what I did (in retrospect, I probably should've used lodash's `once`, but I didn't know about that at the time):

```typescript
export function lazy<T>(init: () => Promise<T>): () => Promise<T> {
  let result: Promise<T>;

  return () => {
    if (!result) { result = init(); }
    return result;
  };
}
```

Then, in my service, I can use it like this:
```typescript
const getMixpanel = lazy(async () => Mixpanel.init('my key'));
```

And I can await that promise before calling the `logEvent` function.

```typescript
const instance = await getMixpanel();
instance.logEvent('my event');
```

I like having the service as an abstraction to isolate the init logic.  You could also use a hook like `useMixpanel` and have it return a `Promise<Mixpanel>`.

I have both the service and a hook.  I call `useLogEvent('my event')` and it returns a `logEvent` function and a `logHandler` function.  The `logHandler` function wraps another function with logging.

Something like this:

```typescript
const { logHandler, logEvent } = useLogEvent('User Did Something Important');

// ...

const onPress = () => {
  // do important stuff

  // I can log like this
  logEvent({ customData: 'go here' });
}

// or, if I have a component that takes a handler as a prop, I can log like this
const { onSomeEvent } = props;
const loggedHandler = logHandler(onSomeEvent, { customData: 'go here' });

return (
  <>
    <button onPress={loggedHandler} />
    <button onPress={onSavePressed} />
  </>
);
```

**Comment by zihejia** [comment]
The Mixpanel class method `init()` is potentially causing issues and we are now deprecating it. 
Please try our latest version 1.3.1 and use the instance method `init()` instead. 
```
import { Mixpanel } from 'mixpanel-react-native';

const mixpanel = new Mixpanel("Your Project Token");
mixpanel.init();
```

More examples: https://github.com/mixpanel/mixpanel-react-native/tree/master/Samples. 

This folder contains 3 sample applications demonstrating how you can use Mixpanel in your React Native app. 

SimpleMixpanel: Integrate Mixpanel with a minimalist approach
MixpanelDemo: A full Mixpanel API demo app
ContextAPIMixpanel: Integrate Mixpanel with Context API

I'm closing this one now. Please feel free to reopen if you have any issues. Again, thanks so much for bringing it up.

**Comment by jamesdunay** [comment]
I just installed the latest. "mixpanel-react-native": "^1.3.1". And I'm getting this back... 

`[TypeError: mixpanel.init is not a function. (In 'mixpanel.init()', 'mixpanel.init' is undefined)]`

**Comment by zihejia** [comment]
hi @jamesdunay , sorry for the inconvenience. This is a known issue and we will address this shortly. For the time being, you can follow the workaround in here: https://github.com/mixpanel/mixpanel-react-native/issues/83

**Comment by dan-f** [comment]
Hi @zihejia, despite the API change, you still provide a method named `init` which returns a promise. Can you please confirm whether it's necessary to `await` the result of `mixpanel.init()` in order for the mixpanel instance to function properly?

Both your [ios](https://github.com/mixpanel/mixpanel-react-native/blob/master/ios/MixpanelReactNative.swift#L15-L25) and [android](https://github.com/mixpanel/mixpanel-react-native/blob/master/android/src/main/java/com/mixpanel/reactnative/MixpanelReactNativeModule.java#L35-L41) implementations synchronously initialize Mixpanel, and immediately resolve the promise. So is initialization not actually asynchronous, or is Mixpanel perhaps buffering events internally so that callers don't need to deal with that detail?

So anyways, just looking for clarity on whether we need to wait on that `init` promise or not.

Thanks!
