### ISSUE TITLE
Mixpanel React Native is null

### ISSUE THREAD

**Issue by darajava** [mixpanel/mixpanel-react-native#71]
I have followed your nice and simple installation steps and this works great on iOS. However on Android it doesn't and I get the following error:

![image](https://user-images.githubusercontent.com/5908229/125927596-dde7fe81-5bfb-480a-a95d-3cb17d586d4b.png)

I deleted node_modules and the issue persisted. 

package.json:
`"mixpanel-react-native": "^1.2.4",`

**Comment by zihejia** [comment]
hi @darajava , could you share how you initialize Mixpanel? Also you can try using this CLI tool to clean your react native project: https://github.com/pmadruga/react-native-clean-project

**Comment by zihejia** [comment]
The Mixpanel class method `init()` is potentially causing issues and we are now deprecating it. 
Please try our latest version 1.3.1 and use the instance method `init()` instead. We've updated all our docs.
```
import { Mixpanel } from 'mixpanel-react-native';

const mixpanel = new Mixpanel("Your Project Token");
mixpanel.init();
```

More examples: https://github.com/mixpanel/mixpanel-react-native/tree/master/Samples. 

This folder contains 3 sample applications demonstrating how you can use Mixpanel in your React Native app. 

SimpleMixpanel: Integrate Mixpanel with a minimalist approach
MixpanelDemo: A full Mixpanel API demo app
ContextAPIMixpanel: Integrate Mixpanel with Context API

I'm closing this one now. Please feel free to reopen if you have any issues. Again, thanks so much for bringing it up.

**Comment by JohnCWakley** [comment]
I am experiencing the same error still, I created my demo as per the instructions.

In `App.js`:
```
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';
import { Mixpanel } from "mixpanel-react-native";

const mixpanel = new Mixpanel("MY_TOKEN");
mixpanel.init();

export default function App() {

  const onPressed = (obj) => {
    console.debug('*** onPressed ***');
    mixpanel.track('MIXPANEL_DEMO_BUTTON_PRESSED', { LABEL: obj.title });
  };

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
      <Text>Click the button below to track a mixpanel event:</Text>
      <Button title={"Click Me!"} onPress={onPressed} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Running with: `$ npm run web`

Error in DevTools:
![image](https://user-images.githubusercontent.com/33690133/127662917-4e062ad4-9355-4db9-9aab-6622e3880bcc.png)

I did run `react-native-clean-project`, but that did not help.

`package.json`:
```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start"
  },
  "dependencies": {
    "expo": "~42.0.1",
    "expo-splash-screen": "~0.11.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.8.1",
    "mixpanel-react-native": "^1.3.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-unimodules": "~0.14.5",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "react-native-clean-project": "^3.6.4"
  },
  "private": true
}
```

Google Chrome: Version 92.0.4515.107 (Official Build) (64-bit)

```
$ node --version
v14.17.3

$ npm --version
6.14.13
```

**Comment by zihejia** [comment]
hi @JohnCWakley , currently we don't support flutter web. But we will add the support in future.

**Comment by JohnCWakley** [comment]
@zihejia : I don't understand the reference to flutter web here - do you mean that your product does not support running a ReactNative app using the npm script `web` in the project above?

**Comment by zihejia** [comment]
oh, sorry, I mean react native web.

**Comment by JohnCWakley** [comment]
Ah, ok, thank you.

**Comment by hyochan** [comment]
@zihejia I've tried this in react-native-web and this isn't working. I can't prevent this using `Platform.OS === 'web'`, because it throws error just by importing the module.
