### ISSUE TITLE
Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId

### ISSUE THREAD

**Issue by aforty** [mixpanel/mixpanel-react-native#75]
I can't seem to even initialize. Why is it looking for firebase instanceid? Pretty sure that's been deprecated.

![Screen Shot 2021-07-21 at 14 08 21](https://user-images.githubusercontent.com/523683/126538600-318a054e-8f69-4d74-9d85-e4161e618e11.png)

**Comment by zihejia** [comment]
hi @aforty , thanks for bringing it up. Which Mixpanel SDK version you are using?

**Comment by aforty** [comment]
Hi I just installed latest version of `mixpanel-react-native` and went through installation instructions @ https://developer.mixpanel.com/docs/react-native-quickstart

**Comment by zihejia** [comment]
hi @aforty , you can try adding these in App's Build grade dependencies as a workaround. We will fix it on the Android Sdk.

```
implementation platform('com.google.firebase:firebase-bom:28.0.1')
implementation("com.google.firebase:firebase-iid")
```
https://github.com/mixpanel/mixpanel-android/issues/744

**Comment by aforty** [comment]
Thanks!
