### ISSUE TITLE
confusion re documentation

### ISSUE THREAD

**Issue by pritamsoni-hsr** [mixpanel/mixpanel-react-native#77]
[types says optInTracking](https://github.com/mixpanel/mixpanel-react-native/blob/16f01a1731cefeb6cf27f85f7033408e0880f63d/index.d.ts#L5) but this is mapped to [optOutTrackingDefault](https://github.com/mixpanel/mixpanel-react-native/blob/16f01a1731cefeb6cf27f85f7033408e0880f63d/index.js#L61)

and on iOS and android it uses the [same prop name, optOutTrackingDefault](https://github.com/mixpanel/mixpanel-react-native/blob/16f01a1731cefeb6cf27f85f7033408e0880f63d/ios/MixpanelReactNative.swift#L16) 

and option to enable debug mode, the init method in js should take in an optional `debug` boolean and update the metadata object with this value.

**Comment by zihejia** [comment]
hi @pritamsoni-hsr , thanks for bringing it up. I will fix it.
