### ISSUE TITLE
iOS Simulator: sync not working as expected

### ISSUE THREAD

**Issue by chris-schra** [mixpanel/mixpanel-react-native#81]
Just installed the package in our app, running in simulator with logging enabled. 
The docs state that the data is flushed every 60 seconds, but at least in Simulator nothing happens - no timer or so. But when I send the app to background, the data is eventually flushed and visible in Mixpanel's dashboard.

It looks like the app has to be sent to background at least once to start the timer for flushing the data

**Comment by tushar-singhal** [comment]
I have facing the same issue, on iOS, events are only recorded when I send the app to background. Otherwise I dont see anything in Mixpanel's dashboard.

On Android, I don't see any events tracked at all, not even after sending the app to background

**Comment by zihejia** [comment]
Sorry for the late response and Thanks for bringing it up! There was an issue that might cause the iOS flush timer to stop working. It's been fixed in v1.3.5! Now it should flush for every 60s by default. I'm closing this issue now, please feel free to reopen if the problem still exists.
