### ISSUE TITLE
[Android] Build fails after Maven migration

### ISSUE THREAD

**Issue by iamandiradu** [mixpanel/mixpanel-react-native#94]
JCenter is shutting down resulting in many libraries failing on build. This one is no exception.

I'll prepare a PR replacing JCenter with Maven.

**Comment by zihejia** [comment]
it's been fixed in [v1.3.3 ](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v1.3.3). Closing this one now. Thanks @iamandiradu !
